### ISSUE TITLE
Feedback: Retrieve Cart Contents / Add Item To Cart Endpoints

### ISSUE THREAD

**Issue by donmb1** [co-cart/co-cart#105]
Great work with this project! I really enjoy using it.
However, I have some basic feedback or maybe I was not able to properly find the related answer in your docs:

https://docs.cocart.xyz/#retrieve-cart-contents

From the docs it is not clear how to retrieve the User ID of the "logged in customer" or the "guest customer".

Also: https://docs.cocart.xyz/#add-item-to-cart
It seems not intuitive how to add an item to an existing cart.
By nature I would try to retrieve the current cart hash (cookies) and then add items to it.
We get the `woocommerce_cart_hash` in cookies. We should be able to pass this one as parameter in the post request maybe to be able to add items to the cart.

**Comment by deniskabana** [comment]
@seb86 why was this closed? There is no closure here.

>It seems not intuitive how to add an item to an existing cart.
This is a very great point and is lacking in documentation.

**Comment by seb86** [comment]
@deniskabana This is closed because another issue related is already open and is still in the works. The documentation supports what is currently available, nothing more.
