### ISSUE TITLE
Providing Node.js example

### ISSUE THREAD

**Issue by TimNZ** [co-cart/co-cart#109]
I hope this gist is useful for people using CoCart from Node.js.

https://gist.github.com/TimNZ/93c94888eef7e2bee67860238929d60d

* Uses axios-cookiejar-support package to support auto capture and sending of Cookies in requests
* Confirmed that as guest users, each session is separate, allowing this to scale - just don't provide any authentication.

Maybe you want to add more complete examples to the documentation.
It might also be good to make more explicit in https://docs.cocart.xyz/#authentication that guest mode i.e. no authentication, should be used if you just want the calculation done without concern for a specific user.

**Comment by seb86** [comment]
Hi @TimNZ 

Thanks for sharing the snippet. Would it be possible for you to apply Node.js to the [documentation directly](https://github.com/co-cart/co-cart-docs)?

> Maybe you want to add more complete examples to the documentation.
> It might also be good to make more explicit in docs.cocart.xyz/#authentication that guest mode i.e. no authentication, should be used if you just want the calculation done without concern for a specific user.

I have a note explaining the authentication purposes.

`Authentication is only required for registered customers, not guest customers ...`

**Comment by TimNZ** [comment]
I feel explicitly saying at the top of Authentication section that you only need to Authenticate for explicit user session cart management, would have saved me time experimenting - I started off thinking you HAD to authenticate.

That note re Guest access doesn't stick out.

Then I was started getting concerned about how to handle scale i.e. simultaneous usage for different cart calculations, which resulted in the Gist.

Making that clear would have saved me a bunch of time.

**Comment by seb86** [comment]
OK I will move the notice up in my next documentation update.

**Comment by seb86** [comment]
Created [new issue for this](https://github.com/co-cart/co-cart-docs/issues/23).
