### ISSUE TITLE
managed_products & out of stock: Error 500

### ISSUE THREAD

**Issue by metemaddar** [co-cart/co-cart#113]
Hello, Thanks again for great plugin.
When we check the "Manage Stock Amount" on product. and we run out of product while adding, The API faces error 500.
Unfortunately I couldn't detect the cause from error_log. <a href="https://stackoverflow.com/questions/7149030/php-return-500-error-but-no-error-log">Maybe because of the way using some functions so that php did not log the error</a>.

**So how to regenerate the situation:**
We should make a product with "managed stock amount" in product admin.
For example we set the stock amount to 2;
and when we add the first two products, it is ok. But when we request another one to add to basket, The API returns error 500

**Comment by seb86** [comment]
@metemaddar So your saying the error message did not return. Just told that it was an error, correct?

**Comment by seb86** [comment]
@metemaddar You should have got the error code "cocart_not_enough_stock_remaining" I don't see a bug here after running a local test.

What your doing is correct. If you only have 2 left in stock and you try to add the item again to increase the quantity to 3, it will not add it.

**Comment by metemaddar** [comment]
Oh. You are true. I didn't pay attention to the body of the response.

**Comment by seb86** [comment]
OK
