### ISSUE TITLE
wp-json/cocart/v1/totals throws error

### ISSUE THREAD

**Issue by gauravbordoloi** [co-cart/co-cart#116]
After I updated to the latest version yesterday night, I am receiving this 2 errors.

WHILE CALCULATING TOTAL ->

> CRITICAL Uncaught Error: Call to undefined method CoCart_Calculate_Controller::get_totals() in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/cart-rest-api-for-woocommerce/includes/api/class-cocart-calculate-controller.php:65
> Stack trace:
> #0 /opt/bitnami/apps/wordpress/htdocs/wp-includes/rest-api/class-wp-rest-server.php(1015): CoCart_Calculate_Controller->calculate_totals(Object(WP_REST_Request))
> #1 /opt/bitnami/apps/wordpress/htdocs/wp-includes/rest-api/class-wp-rest-server.php(342): WP_REST_Server->dispatch(Object(WP_REST_Request))
> #2 /opt/bitnami/apps/wordpress/htdocs/wp-includes/rest-api.php(306): WP_REST_Server->serve_request('/cocart/v1/calc...')
> #3 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(287): rest_api_loaded(Object(WP))
> #4 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
> #5 /opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
> #6 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp. in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/cart-rest-api-for-woocommerce/includes/api/class-cocart-calculate-controller.php on line 65

I am also receiving this error, when I am trying to uninstall the plugin from dashboard ->

> CRITICAL Uncaught Error: Class 'CoCart_Install' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/cart-rest-api-for-woocommerce/uninstall.php:16
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/plugin.php(1222): include()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/plugin.php(956): uninstall_plugin('cart-rest-api-f...')
#2 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/ajax-actions.php(4545): delete_plugins(Array)
#3 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(287): wp_ajax_delete_plugin('')
#4 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#6 /opt/bitnami/apps/wordpress/htdocs/wp-admin/admin-ajax.php(175): do_action('wp_ajax_delete-...')
#7 {main}
thrown in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/cart-rest-api-for-woocommerce/uninstall.php on line 16

**Comment by gauravbordoloi** [comment]
I am also unable to uninstall, throwing this error.

CRITICAL Uncaught Error: Class 'CoCart_Install' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/cart-rest-api-for-woocommerce/uninstall.php:16
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/plugin.php(1222): include()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/plugin.php(956): uninstall_plugin('cart-rest-api-f...')
#2 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/ajax-actions.php(4545): delete_plugins(Array)
#3 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(287): wp_ajax_delete_plugin('')
#4 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /opt/bitnami/apps/wordpress/htdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#6 /opt/bitnami/apps/wordpress/htdocs/wp-admin/admin-ajax.php(175): do_action('wp_ajax_delete-...')
#7 {main}
  thrown in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/cart-rest-api-for-woocommerce/uninstall.php on line 16

This is happening after I updated the plugin yesterday night

**Comment by seb86** [comment]
Thank you for reporting this @gauravbordoloi

**Comment by seb86** [comment]
Fixed. Pushing HOTFIX.

**Comment by gauravbordoloi** [comment]
Great to see issue was fixed on the same day :)

**Comment by martin-swiftcom** [comment]
Hi, I'm experiencing this same issue on the latest versions (2.6.3 and 2.7.0). I also had to roll back to v2.0.13 to solve the issue for now

[05-Oct-2020 18:04:46 UTC] PHP Fatal error:  Uncaught Error: Call to a member function calculate_totals() on null in /public_html/wp-content/plugins/co-cart-master/includes/api/class-cocart-calculate-controller.php:67
Stack trace:
#0 /public_html/wp-includes/rest-api/class-wp-rest-server.php(1050): CoCart_Calculate_Controller->calculate_totals(Object(WP_REST_Request))
#1 /public_html/wp-includes/rest-api.php(464): WP_REST_Server->dispatch(Object(WP_REST_Request))
#2 /public_html/wp-content/plugins/cart-interface/cart.php(142): rest_do_request(Object(WP_REST_Request))
#3 /public_html/wp-content/plugins/cart-interface/cart.php(68): cart_calculate_totals(Object(WP_REST_Request))
#5 /public_html/wp-content/plugins/co-cart-master/includes/api/class-cocart-calculate-controller.php on line 67

**Comment by seb86** [comment]
Not the exact same error. This issue is closed so please create a fresh bug issue and use the template provided. Thank you @martin-swiftcom
