### ISSUE TITLE
ISBAT: See customers cart synchronized

### ISSUE THREAD

**Issue by seb86** [co-cart/co-cart#117]
**Is this enhancement related to a problem? Please describe.**

Now that CoCart has it's own session handler, there is currently a down side to synchronising carts should a developer not use the load cart from session feature and the same vs.

Meaning a customer can start adding items via the headless app but not see the same cart via the web.

**Describe the solution you'd like**

There are two methods to solving this. The first might be the easiest which is to filter the WooCommerce session handler to use CoCart's session handler so the same session handler is used for both the web and app.

The second would be a little more challenging by using meta to identify where the customer is and update the cart.

**Additional context**

This would need to be discussed with users.

**Comment by WebWolfRus** [comment]
I think will be good first :)

**Comment by seb86** [comment]
Thank you for reporting the issue @WebWolfRus

**Comment by seb86** [comment]
@WebWolfRus Can you try out [this branch](https://github.com/co-cart/co-cart/tree/sync) please to test cart sync for registered customers?

There is a new debug tool labelled "**Synchronize carts**" that will copy carts over to CoCart's session table under "WooCommerce -> System Status".

**Comment by WebWolfRus** [comment]
Thank! We wait. It is very cool!
So there is a problem with authorization, we enter Authorization ":" Basic bWloYTkwNQ == then after switching to another page, then authorization fails. It would be cool to come up with a solution for an authorized user session as well.

**Comment by seb86** [comment]
@WebWolfRus Have you already tried the branch? Did you authorize the customer on the other page too?

**Comment by WebWolfRus** [comment]
Yes, I got it, I open it in the browser like this. /my-account/?cocart-load-cart=$idcart
headers: {"Authorization": "Basic bWloYkwNQ =="},
And everything is fine, but as soon as I go to any other page, everything goes astray .. the basket remains, but the user is no longer logged in.

That is, here the basket was transmitted to the user immediately by id and everything works well on one page, but when you place an order qualitatively it is issued as a guest. Moreover, all fields of the order form are already filled with parameters from the (address) user profile

**Comment by seb86** [comment]
Only the cart data is loaded as stated in the documentation. As for the authentication issue, I thought your customer was already logged in via the web?

**Comment by WebWolfRus** [comment]
No, the client is not logged in. I am trying to authorize it through basic authorization. (Authorization: Basic). Maybe in the future you will have some kind of simple authorization solution as you did for transferring the cocart-load-cart basket it would be very cool.

**Comment by seb86** [comment]
I don' think that is possible otherwise it would already be supported in the core of WordPress.

**Comment by seb86** [comment]
Can you give me the code snippet you are using to do this while loading the cart to the web?

**Comment by WebWolfRus** [comment]
am writing a mobile application on flutter. And inside the application, I open the flutter webview browser with a link to the checkout page. In general, I'm trying to make the same basket on flutter as it is implemented here: https://codecanyon.net/item/oreo-fashion-full-react-native-app-for-woocommerce/24951657 here the order is added to the basket and then the client just throw on the checkout page in the browser. You can download an example application to see what I'm trying to achieve using your plugin)

**Comment by seb86** [comment]
I'm trying to understand the authentication but without some code, cant help.

**Comment by seb86** [comment]
> 
> 
> No, the client is not logged in. I am trying to authorize it through basic authorization. (Authorization: Basic). Maybe in the future you will have some kind of simple authorization solution as you did for transferring the cocart-load-cart basket it would be very cool.

You should read this article as to why you cant log in a user on the web via the REST API. https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

**Comment by WebWolfRus** [comment]
Thank you so much! :) Waiting for Synchronize carts update :)

**Comment by seb86** [comment]
This release should fix this issue. [v2.1.2-rc.1](https://github.com/co-cart/co-cart/releases/tag/v2.1.2-rc.1)

**Comment by WebWolfRus** [comment]
WOW nice!! Thanks!!!

**Comment by seb86** [comment]
Look forward to your feedback. Thank you @WebWolfRus

**Comment by seb86** [comment]
Looks like the issue is resolved. Customer did a live test with me via video chat so I am closing this issue.
