### ISSUE TITLE
Filtered `nonce_user_logged_out` is incorrect for frontend purposes causing users logged out to fail verification.

### ISSUE THREAD

**Issue by artemverbo** [co-cart/co-cart#121]
Hi!

Please advise, having some issues with cookies/sessions when Co Cart plugin is enabled.

When trying to register or login via /my-account standard Woo Commerce page:
1) Correct login credentials login silently fails (page resubmits on itself, but session and logged-in cookies are not set).
2) Incorrect login credentials or registration validation problems are not displayed (without Co Cart they are displayed via Woo Commerce default notice alert)

Default WP login (/wp-admin) works fine.

WP: 5.4.2
Report:

`
### WordPress Environment ###

WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_NZ
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.1
PHP Version: 7.2.26
PHP Post Max Size: 128 MB
PHP Time Limit: 3000
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.29
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Active Plugins ###

Adminimize: by Frank Bültge – 1.11.6
Advanced Custom Fields PRO: by Elliot Condon – 5.8.12
Age Gate: by Phil Baker – 2.5.3
CoCart: by Sébastien Dumont – 2.1.4
Classic Editor: by WordPress Contributors – 1.5
CoCart Pro: by Sébastien Dumont – 1.0.0-rc.3 – Installed version not tested with active version of WooCommerce 4.2.0
GDPR Cookie Consent: by WebToffee – 1.8.8
Google Tag Manager for Wordpress: by Thomas Geiger – 1.11.4 – Installed version not tested with active version of WooCommerce 4.2.0
Import Users from CSV: by Andrew Lima – 1.0.1
PW WooCommerce Gift Cards Pro: by Pimwick
LLC – 1.226

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.16.26.24

User Role Editor: by Vladimir Garagulya – 4.55.1
WooCommerce Stripe Gateway: by WooCommerce – 4.4.0 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.15 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Subscriptions: by WooCommerce – 3.0.4 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce: by Automattic – 4.2.0
Yoast SEO: by Team Yoast – 14.3
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.15
WP Migrate DB Pro Theme & Plugin Files: by Delicious Brains – 1.0.5
WP Migrate DB Pro: by Delicious Brains – 1.9.10
WP Offload SES Lite: by Delicious Brains – 1.4.1
YITH WooCommerce Email Templates Premium: by YITH – 1.3.26
YITH WooCommerce Role Based Prices Premium: by YITH – 1.2.2

### CoCart ###

Version: 2.1.4
Database Version: 2.1.4
Install Date: November 18
2019

Carts in Session: 636
Carts Expired: 0

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

### Action Scheduler ###

Complete: 76
Oldest: 2020-06-09 15:11:06 +1200
Newest: 2020-06-12 11:55:29 +1200

Pending: 1
Oldest: 2021-02-11 15:39:15 +1300
Newest: 2021-02-11 15:39:15 +1300

`

**Comment by seb86** [comment]
@artemverbo Update coming.

**Comment by seb86** [comment]
The issue was that the value returned for `nonce_user_logged_out` filter was not returning `0`. This is how WordPress understands a logged out user via the frontend. The problem before I added guest support was that `0` was not ideal for a headless architecture and this filter was overlooked when developing a new session handler for guest customers to work.
