### ISSUE TITLE
Shipping Rate

### ISSUE THREAD

**Issue by thisisjaiswal** [co-cart/co-cart#13]
Now as you have the api to manage cart, are you planning to add one for calculating shipping rates?

**Comment by seb86** [comment]
You can if you like [contribute](https://github.com/seb86/WooCommerce-Cart-REST-API/blob/master/CONTRIBUTING.md) to the project and be credited for it.

**Comment by IntelliJAbhishek** [comment]
yes @seb86 it would be great if we can apply coupons and choose shipping methods this will best plugin for developers. You are doing great work woocommerce provided us half baked rest api.

**Comment by seb86** [comment]
Thank you @IntelliJAbhishek
