### ISSUE TITLE
Add the use of NAMESPACES

### ISSUE THREAD

**Issue by seb86** [co-cart/co-cart#140]
Eventually the use of NAMESPACES could help with a number of things including packaging the plugin much easier into CoCart Pro and speed for those using PHP 8+

**The solution I'd like**

Include namespaces on all PHP files that are using a class system. This does not include global functions or template files, just class files.

### Example

```php
namespace CoCart\CoCartLite\RestAPI;
```

Then the namespace can be used like so where needed.

```php
use CoCart\CoCartLite\RestAPI;
```

**Comment by elaynelemos** [comment]
Hey! I can work on it for hacktoberfest. Could you assign it to me?

**Comment by seb86** [comment]
There you go and thank you.

**Comment by seb86** [comment]
Don't forget it's for the **[v3.0.0](https://github.com/co-cart/co-cart/tree/v3.0.0)** branch.

**Comment by elaynelemos** [comment]
> Don't forget it's for the **[v3.0.0](https://github.com/co-cart/co-cart/tree/v3.0.0)** branch.

Ok!

**Comment by seb86** [comment]
Any update on this yet @elaynelemos

**Comment by seb86** [comment]
Will open again if this is really needed.

**Comment by seb86** [comment]
If you have any questions, please let me know. Thank you.

**Comment by seb86** [comment]
Finally got round to adding namespaces. Still a work in progress [on the dev branch](https://github.com/co-cart/co-cart/tree/dev) which will be the new master branch.

**Comment by seb86** [comment]
I'm still deciding on how to use Namespaces for the API it's self.

**Comment by seb86** [comment]
Closing this issue now. Leaving the API as is.
