### ISSUE TITLE
Mutating the cart should always return the updated cart object

### ISSUE THREAD

**Issue by DonKoko** [co-cart/co-cart#144]
**Is this enhancement related to a problem? Please describe.**
Currently when using certain endpoints that mutate the cart, we need to then manually do another request to update the cart.

**Describe the solution you'd like**
Each call to cart that changes its state in any way, should return the updated cart. This way it will be super easy and way more performant to keep your client side cart always up-to-date and now worry about inconsistencies and so on.

**Additional context**
When I have worked before with a cart api it worked in that way and I thought it was way easier to guarantee there are no data inconsistencies. Here is the API I am referring to: https://documentation.elasticpath.com/commerce-cloud/docs/api/carts-and-checkout/carts/index.html

**Comment by seb86** [comment]
Similar issue #137

**Comment by seb86** [comment]
Could you provide a workflow example @DonKoko ?

**Comment by DonKoko** [comment]
I kinda missed this comment. I have worked so far with 1 headless webshop API and it worked in this way and I found it extremely useful.
The concept is that any call to the API that mutates the cart, should return the new cart value. That way it can easily be updated in the state, without doing a manual merge. This way we can guaranteed that our cart in our frontend state is 1:1 with the cart in on the server.

Actions that will return cart for example are:

- Add to cart
- Add variation to cart
- Restore item to cart
- Remove from cart
- Update cart item
- Apply coupon
- Calculate shipping
- Calculate totals
- Count items
- Add fees
- Remove fees
etc.

You get the gist of it. If it modifies the cart, it should return the cart.

This will prevent me having to do multiple requests and will make our apps more performant as we can achieve more with less requests to the server.

**Comment by seb86** [comment]
@DonKoko Why would the cart return for counting the items?

**Comment by DonKoko** [comment]
You are correct. Count items shouldn't be there. I edited my comment. Maybe another good way to explain it is that its for all requests types except `GET`.

**Comment by seb86** [comment]
Works and ready for CoCart Lite. Will be applying the same to CoCart Pro in a future update when CoCart v3.0.0 is ready for launch.
