### ISSUE TITLE
Uncaught Error: Undefined class constant `E_WC_ADMIN_NOTE_MARKETING`

### ISSUE THREAD

**Issue by hammadtariq98** [co-cart/co-cart#146]
Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, CoCart.

WordPress version 5.4.2
Current theme: Mein Glaswerk (version 2.4.3.1589892624)
Current plugin: CoCart (version 2.5.1)
PHP version 7.1.33-17+0~20200807.39+debian9~1.gbp032d47

Error Details
=============
```php
An error of type E_ERROR was caused in line 84 of the file /home/www/wordpress/wp-content/plugins/cart-rest-api-for-woocommerce/includes/admin/notes/class-cocart-wc-admin-note-do-with-products.php.
Error message: Uncaught Error: Undefined class constant 'E_WC_ADMIN_NOTE_MARKETING' in /home/www/wordpress/wp-content/plugins/cart-rest-api-for-woocommerce/includes/admin/notes/class-cocart-wc-admin-note-do-with-products.php:84
Stack trace:
#0 /home/www/wordpress/wp-content/plugins/cart-rest-api-for-woocommerce/includes/admin/notes/class-cocart-wc-admin-note-do-with-products.php(45): CoCart_WC_Admin_Do_With_Products_Note::get_note_args()
#1 /home/www/wordpress/wp-content/plugins/cart-rest-api-for-woocommerce/includes/admin/notes/class-cocart-wc-admin-note-do-with-products.php(30): CoCart_WC_Admin_Do_With_Products_Note::add_note('cocart-wc-admin...')
#2 /home/www/wordpress/wp-content/plugins/cart-rest-api-for-woocommerce/includes/admin/notes/class-cocart-wc-admin-note-do-with-products.php(102): CoCart_WC_Admin_Do_With_Products_Note->__construct()
#3 /home/www/wordpress/wp-content/plugins/cart-rest-api-for-woocommerce/includes/admin/class-cocart-wc-admin-notices.php(52): include_once('/home/www/wordp...')
#4 /home/www/wordpre
```

**Comment by seb86** [comment]
@hammadtariq98 If this error occurred when updating the plugin then do you have the latest version of WooCommerce?

**Comment by hammadtariq98** [comment]
@seb86  Yes I have the latest version

**Comment by seb86** [comment]
I'm not able to replicate the issue @hammadtariq98 

Could you `copy` and `paste` your **WooCommerce System Status** report here please?

**Comment by seb86** [comment]
As I said @hammadtariq98 I was not able to replicate the issue but I have improved verification loading notes in the next update.

**Comment by hammadtariq98** [comment]
Sorry for the late reply 

The version is:

4.2.0 - 2020-06-02

for WooCommerceIt is not the latest version.

**Comment by seb86** [comment]
I asked for your WooCommerce System Status report please.

**Comment by hammadtariq98** [comment]
### WordPress Environment ###

WordPress address (URL): http://www.meinglaswerk.de
Site address (URL): http://www.meinglaswerk.de
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.22-1+0~20200909.67+debian9~1.gbpdd7b72
PHP Post Max Size: 150 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 8.0.15
Max Upload Size: 150 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: gowp_
Total Database Size: 33.67MB
Database Data Size: 30.97MB
Database Index Size: 2.70MB
gowp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
gowp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
gowp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
gowp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_cocart_carts: Data: 0.41MB + Index: 0.02MB + Engine InnoDB
gowp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
gowp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_options: Data: 6.48MB + Index: 0.06MB + Engine InnoDB
gowp_postmeta: Data: 13.52MB + Index: 0.59MB + Engine InnoDB
gowp_posts: Data: 3.52MB + Index: 0.22MB + Engine InnoDB
gowp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gowp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
gowp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gowp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
gowp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
gowp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gowp_wfconfig: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
gowp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_wffilemods: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
gowp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gowp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_wfissues: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
gowp_wfknownfilelist: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
gowp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_wflogins: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
gowp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
gowp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
gowp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
gowp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
gowp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
gowp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

astra_adv_header: 1
attachment: 75
custom_css: 2
custom-css-js: 2
elementor_library: 2
elementor-hf: 4
nav_menu_item: 48
page: 18
post: 4
product: 18
revision: 692
wpmm_theme: 3

### Security ###

Secure connection (HTTPS): :x:
Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (17) ###

AJAX Search for WooCommerce: by Damian Góra – 1.7.1 – Installed version not tested with active version of WooCommerce 4.2.0
All-in-One WP Migration: by ServMask – 6.77
Astra Pro: by Brainstorm Force – 2.5.1
WP Portfolio: by Brainstorm Force – 1.9.0
Child Theme Configurator: by Lilaea Media – 2.5.5
Simple Custom CSS and JS: by SilkyPress.com – 3.31.1 – Installed version not tested with active version of WooCommerce 4.2.0
Duplicate Post: by Enrico Battocchi – 3.2.4
Elementor Pro: by Elementor.com – 2.10.2
Elementor: by Elementor.com – 2.9.12
Elementor - Header, Footer & Blocks: by Brainstorm Force
Nikhil Chavan – 1.5.1

Password Protected: by Ben Huson – 2.3
Really Simple SSL: by Really Simple Plugins – 3.3.4
Ultimate Addons for Elementor: by Brainstorm Force – 1.24.3
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.7
WooCommerce: by Automattic – 4.2.0 (update to version 4.5.2 is available)
Wordfence Security: by Wordfence – 7.4.11
WP Mail SMTP: by WPForms – 2.1.1

### Inactive Plugins (2) ###

CoCart: by Sébastien Dumont – 2.6.1
Coming Soon Page, Under Construction & Maintenance Mode by SeedProd: by SeedProd – 5.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #20 - /checkout/
My account: #21 - /mein-konto/
Terms and conditions: :x: Page not set

### Theme ###

Name: Mein Glaswerk
Version: 2.4.3.1589892624
Author URL: https://meinglaswerk.de
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 2.4.5 – 2.5.5 is available
Parent Theme Author URL: https://wpastra.com/about/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

**Comment by seb86** [comment]
Didn't know you were not the client @hammadtariq98 

Can you please confirm that the latest update of CoCart has solved the issue with the current version of WooCommerce your client has installed. Thank you.

**Comment by hammadtariq98** [comment]
Ok, no problem.
So you said there is no need to update wooComerece right?

**Comment by seb86** [comment]
No need to update WooCommerce just update CoCart.

**Comment by hammadtariq98** [comment]
Thank bro But bad luck. I updated  CoCart but the site crashes again :-(

**Comment by seb86** [comment]
Try installing WooCommerce Admin.

**Comment by hammadtariq98** [comment]
But why? is it compulsory?

**Comment by seb86** [comment]
I want to know if it will remove the error. If it does I will have to bump the if statement for the notes to a higher WooCommerce version.

**Comment by seb86** [comment]
If you update WooCommerce it will contain the latest version of WC Admin too but please only do so if you have backed up before which is why I said to install WC Admin only.

**Comment by hammadtariq98** [comment]
ok let me check on this with the client then I will get back to you. Thank you

**Comment by seb86** [comment]
Thank you for the pull request @dmchale  Let me know if you are doing the Hacktoberfest and I will assign you to this issue.

**Comment by dmchale** [comment]
I am, cheers 😀 Please let me know if you take any issue with my solution
here! Defaulting back to "info" seemed the best course of action to me.

**Comment by seb86** [comment]
Thank you for fixing this issue @dmchale

**Comment by dmchale** [comment]
Happy to help, @seb86 !

**Comment by hammadtariq98** [comment]
@seb86  yet I did not get a solution

**Comment by seb86** [comment]
Patch will be in the next release scheduled for 14th October. You can test the latest release candidate and see if that helps for the time being.

**Comment by hammadtariq98** [comment]
I used but why it gives `400 error`

`var settings = {
    ...headers,
    "url": `${wpUrl}/add-item`,
    "method": "POST",
    "data": {
      "product_id" : ID,
      "quantity" : 1,
      "cart_item_data" : state // object
    }
  };
 

  console.log(settings);

  $.ajax(settings).done(function (response) {
    if(response){
      console.log("order update Submited",window.parent.location.href)
      window.parent.location.href = window.parent.location.href
    }
  })`

**Comment by seb86** [comment]
@hammadtariq98 Support is not done here.
