### ISSUE TITLE
PHP Fatal error: Uncaught Error: Call to a member function calculate_totals() on null

### ISSUE THREAD

**Issue by martin-swiftcom** [co-cart/co-cart#152]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

In another plugin I used the WordPress internal rest request function (rest_do_request) to request the cart total from  /wp-json/cocart/v1/calculate

## Expected/actual behaviour

I was expecting to see the cart total returned from the internal rest request

When I follow those steps, I see the following error
PHP Fatal error: Uncaught Error: Call to a member function calculate_totals() on null in /public_html/wp-content/plugins/co-cart-master/includes/api/class-cocart-calculate-controller.php:67
Stack trace:
#0 /public_html/wp-includes/rest-api/class-wp-rest-server.php(1050): CoCart_Calculate_Controller->calculate_totals(Object(WP_REST_Request))
#1 /public_html/wp-includes/rest-api.php(464): WP_REST_Server->dispatch(Object(WP_REST_Request))
#2 /public_html/wp-content/plugins/cart-interface/cart.php(142): rest_do_request(Object(WP_REST_Request))
#3 /public_html/wp-content/plugins/cart-interface/cart.php(68): cart_calculate_totals(Object(WP_REST_Request))
#5 /public_html/wp-content/plugins/co-cart-master/includes/api/class-cocart-calculate-controller.php on line 67

## Isolating the problem

- [x] This bug happens with only WooCommerce and CoCart plugin are active.
- [x] This bug happens with a default WordPress theme active.
- [x] This bug happens with the latest release of WooCommerce active.
- [x] This bug happens when I don't authenticate
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment

tested with cocart 2.6.3 and 2.7.0 (latest)

<details>
```
`
### WordPress Environment ###

WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.3.22-1+0~20200909.67+debian9~1.gbpdd7b72
PHP Post Max Size: 30 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.52.1
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.46-MariaDB-1~stretch
Max Upload Size: 30 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: wp_
Total Database Size: 16.80MB
Database Data Size: 12.36MB
Database Index Size: 4.44MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bv_ip_store: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cocart_carts: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_jet_post_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jet_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.14MB + Engine InnoDB
wp_postal_code_coordinates: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 5.52MB + Index: 2.20MB + Engine InnoDB
wp_posts: Data: 1.23MB + Index: 0.28MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.33MB + Index: 0.31MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 117
acf-field-group: 16
action_monitor: 540
attachment: 136
elementor_library: 3
oembed_cache: 4
page: 5
post: 13
product: 7
reviews: 4
revision: 298

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (15) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.9.1
Breeze: by Cloudways – 1.1.8
CoCart: by Sébastien Dumont – 2.0.13 – Installed version not tested with active version of WooCommerce 4.5.2
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 3.2.6
JWT Authentication for WP-API: by Enrique Chavez – 1.2.6
SVG Support: by Benbodhi – 2.3.18
WooCommerce: by Automattic – 4.5.2
Yoast SEO: by Team Yoast – 14.9 – Installed version not tested with active version of WooCommerce 4.5.2
WP Gatsby: by GatsbyJS
Jason Bahl
Tyler Barnes – 0.4.17

WP GraphiQL: by WPGraphQL
Digital First Media
Jason Bahl – 1.0.1

WPGraphQL for Advanced Custom Fields: by WPGraphQL
Jason Bahl – 0.3.4

WP GraphQL: by WPGraphQL – 0.12.0
WPGraphQL WooCommerce (WooGraphQL): by kidunot89 – 0.5.1 – Installed version not tested with active version of WooCommerce 4.5.2

### Inactive Plugins (2) ###

Add WPGraphQL SEO: by Ash Hitchcock – 4.6.0
JWT Auth: by Useful Team – 1.4.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: ❌ Page ID is set
but the page does not exist

Checkout: ❌ Page ID is set
but the page does not exist

My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Headless Theme
Version: 1.0.1
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 1
Oldest: 2020-09-09 15:32:23 +0000
Newest: 2020-09-09 15:32:23 +0000

Complete: 21
Oldest: 2020-09-09 12:03:24 +0000
Newest: 2020-10-05 18:10:31 +0000

Pending: 2
Oldest: 2020-10-05 19:50:59 +0000
Newest: 2020-10-05 19:50:59 +0000

`
```
</details>

**Comment by seb86** [comment]
Why are you doing an internal request? Can you share your code snippet to test?

**Comment by martin-swiftcom** [comment]
We created an endpoint that returns the results from 4 cocart enpoints combined to reduce the amount of API calls that we were making to the backend server. Here is the effective function. In our code each new internal request is done in its own function, but this better illustrates the flow

function cart_get_all_data($incoming_request)
{
  $return_array = [];
  $incoming_request->set_param("thumb", true);

  $incoming_request->set_route('/cocart/v1/calculate');
  $incoming_request->set_method('POST');
  $return_array["calculate"] = rest_do_request($incoming_request);

  $incoming_request->set_route('/cocart/v1/get-cart');
  $incoming_request->set_method('GET');
  $return_array["cart"] = rest_do_request($incoming_request);

  // Only calculate shipping if there are items in cart
  if (isset($return_array["cart"]->data)) {
    $incoming_request->set_route('/wc_api_cart/v1/calculate_shipping');
    $incoming_request->set_method('GET');
    $return_array["shipping"] = rest_do_request($incoming_request);
  }

  $incoming_request->set_route('/cocart/v1/totals');
  $incoming_request->set_method('GET');
  $return_array["totals"] = rest_do_request($incoming_request);

  return $return_array;
}

**Comment by seb86** [comment]
@martin-swiftcom I don't think your doing it right from what I am reading, plus there are typos and methods incorrectly used. Maybe try something like this.

```php
// Calculate totals, assuming that the cart is not empty.
$request  = new WP_REST_Request( 'POST', '/cocart/v1/calculate' );
$response = rest_do_request( $request );
$data     = $response->get_data();
$headers  = $response->get_headers(); // Return headers if you need it.

// Get cart with thumbnails
$request  = new WP_REST_Request( 'GET', '/cocart/v1/get-cart' );
$request->set_body_params(
    array(
        'thumb' => true,
    )
);
$response = rest_do_request( $request );
$data     = $response->get_data();

// If the cart is not empty, calculate the shipping.
if ( ! empty( $data ) ) {
    $request  = new WP_REST_Request( 'POST', '/cocart/v1/calculate/shipping' );
    $request->set_body_params(
        array(
            'country' => "GB",
        )
    );
    $response = rest_do_request( $request );
    $data     = $response->get_data();
}
```

**Comment by martin-swiftcom** [comment]
If I roll back to v2.0.13 the above works perfectly. 

You can test with just the following, which worked in v2.0.13:

`
function cart_get_all_data($incoming_request)
{
  $return_array = [];
  $incoming_request->set_param("thumb", true);

  $incoming_request->set_route('/cocart/v1/calculate');
  $incoming_request->set_method('POST');
  $return_array["calculate"] = rest_do_request($incoming_request);

  return $return_array;
}
`

**Comment by seb86** [comment]
And what do I pass as the `$incoming_request`?

**Comment by martin-swiftcom** [comment]
It is the incoming request received by a normal endpoint. So I added an endpoint called '/expanded_cart/v1/get_cart_data' for example, then that request is passed to the function above. In this case, the incoming request is the request made to my custom endpoint that is being forwarded to the cocart endpoint. I can provide a large amount of functions to serve as an example?

**Comment by dmchale** [comment]
I believe I found the issue, but I'm not sure how @seb86 wants to address. 

When the `CoCart_Cart_API` class initializes, it calls `maybe_load_cart()` to manually create the WooCommerce cart object if it doesn't otherwise exist. The issue comes from the call to `CoCart_Helpers::is_rest_api_request()` inside of there.

`is_rest_api_request()` is written to see if the request is both 1) a REST request and 2) a route within the "cocart" namespace. This makes logical sense since you wouldn't want to create the cart object for no reason on **all** REST requests, but the issue here is that @martin-swiftcom is trying to execute their own endpoint at `/expanded_cart/v1/get_cart_data`, so naturally it fails this check. That's why `/cocart/v1/calculate` works fine when called directly, but fails when proxied through the custom endpoint. `WC()->cart->calculate_totals()` is calling a method on a null object because of the proxy, since the `$_SERVER['REQUEST_URI']` path isn't in the expected namespace.

I thought initially you could just remove the extra check for the "cocart" string inside of `CoCart_Helpers::is_rest_api_request()`, but quickly realized the negative effects that would have on every other call to that function inside this plugin. Another method of detection is probably preferable, though.

**Comment by martin-swiftcom** [comment]
@dmchale This makes perfect sense! Perhaps I can call maybe_load_cart in the meantime? Are you referring to this function?

`AbstractRoute::maybe_load_cart();`

**Comment by dmchale** [comment]
@martin-swiftcom I was originally referring to `CoCart_Rest_API::maybe_load_cart()`, but if you are looking to copy code into your own accessible function then yes I would probably take from `AbstractRoute::maybe_load_cart()` (because that also takes care of loading the woocommerce include files for you). The one extra thing that `CoCart_Rest_API::maybe_load_cart()` does is a check to see if the user session has switched and handle some logic from there, but I don't know if that's relevant to your application - plus you won't have access to the CoCart object instance anyway, so I don't know if you can easily replicate that piece regardless.

**Comment by seb86** [comment]
Not that I recommend it but would a filter on the returned result here help you @martin-swiftcom ? https://github.com/co-cart/co-cart/blob/master/includes/class-cocart-helpers.php#L338

**Comment by seb86** [comment]
Since this is not an error with CoCart I will lock the conversation.
