### ISSUE TITLE
Reduce default cart expiration

### ISSUE THREAD

**Issue by seb86** [co-cart/co-cart#154]
**Is this enhancement related to a problem? Please describe.**

Shopping online has increased since Covid-19 so having carts in session that last longer than 7 days can be confusing when handling stock.

Since CoCart does not yet have a way to check stock before the cart loads it would best if the cart did not stay for 30 days as currently set.

It can still be filtered to the amount of days the developer wishes to set it as using `cocart_cart_expiration` filter. The same for `cocart_cart_expiring` which needs to be a day lesser than.

**Describe the solution you'd like**

Change the defaults to 6 days for expiring and 7 days for expiration. Look for `set_cart_expiration()` function in `/includes/class-cocart-session-handler.php`

**Comment by HolgerDoerner** [comment]
Hello @seb86!
I have made a PR for this Issue as part of Hacktoberfest 😄

**Comment by seb86** [comment]
Thank @HolgerDoerner You have been assigned to this issue so you get credit.
