### ISSUE TITLE
Multiple items at once

### ISSUE THREAD

**Issue by laurentpetijean** [co-cart/co-cart#159]
Hi,

There is a way to add multiple items at once to the cart ?

I code a mobile application where several hundred elements are added at a time and by performing this addition in a for loop the processing time is extremely long

Thanks in advance.

**Comment by seb86** [comment]
Multiple items can not be added to the cart at once in the core of CoCart. A [batch add-on](https://cocart.xyz/add-ons/batch/) is in development.

**Comment by laurentpetijean** [comment]
Thank you for your prompt response

This add-on is not yet available? Even in beta?

My items are simple products with only "cart_item_data" that would be compatible with this add-on?

Thank you

**Comment by seb86** [comment]
No it's not yet ready. I don't I will be supporting the use of `cart_item_data` in batch form at this time.
