### ISSUE TITLE
add-item endpoint returnes a new cart key ( 'x-cocart-api' in header ) in every request

### ISSUE THREAD

**Issue by Cobretti1** [co-cart/co-cart#169]
In **2.7.0** I read this:

> Once **the first item** is added the cart key is returned under X-CoCart-API and can then be used to continue loading that cart via the cart_key parameter.

When I add the first item to cart, it returnes the cart_key ( 'x-cocart-api' ). I save this locally, and use for the next request. Works fine with '`get-cart`' and '`count-items`' and '`clear`', but when I want to update or delete item via '`item`' endpoint, using this **cart_key** in parameters, `404 cocart_item_not_in_cart`.

When I want to add a new item to this cart (so I add **cart_key** parameter in my request), I got a new 'x-cocart-api' in the header. The new item is not added to the previous cart. 

So I add a new item to cart (as a guest) with these parameters (_`add-item`_ endpoint): 
`{product_id: 32, quantity: 1}
`
It returnes a cart key in header (`x-cocart-api`): _52cbd03cf2061a667133710ecbf381fc_

I get my cart items with these params (_`get-cart`_ endpoint), it **works fine**:
`{thumb: true, cart_key: 52cbd03cf2061a667133710ecbf381fc}`

I want to add a new item, now using the cart_key like this (_`add-item`_ endpoint):
`{product_id: 31, quantity: 1, cart_key: 52cbd03cf2061a667133710ecbf381fc}`

And I got back a new cart key in the header: _9897704c38d763ff469a735d99670370_
And the item is not added to the given cart key in params.

**Comment by seb86** [comment]
Hi @Cobretti1 

Thank you for your report.

First of all this error `cocart_item_not_in_cart` means the item was not in the cart so it either was not there to begin with or the wrong cart loaded. Did you forget to use the `cart_item_key` parameter to select the item to update or delete?

Did you authenticate as a registered customer at any point?

**Comment by seb86** [comment]
@Cobretti1 I have just run a test locally using Postman and the header returned the same cart key all the time. Any more details you can provide will be a big help.

## Steps I made as a guest customer.
1. Get empty cart, returns `fa4f5bb5f014ec2b3a245c1eae2e9966` and no cookie created. Expected.
2. Add an item to cart, returns `cfdb54e9d6d8c67749c3d82eba2db108` and cookie created storing matching cart key.
3. Add same item to cart using cart_key parameter with cookie still used. Returns `cfdb54e9d6d8c67749c3d82eba2db108`
4. Repeat step 3 after deleting cookie. Returns `cfdb54e9d6d8c67749c3d82eba2db108`
5. Update item with cookie still used. Returns `cfdb54e9d6d8c67749c3d82eba2db108`
6. Repeat step 4 after deleting cookie. Returns `cfdb54e9d6d8c67749c3d82eba2db108`

**Comment by seb86** [comment]
If there is no further comments on this issue then I will close it.
