### ISSUE TITLE
Unable to remove last item in cart after update to 2.7.2

### ISSUE THREAD

**Issue by pauld8** [co-cart/co-cart#171]
Recent release 2.7.2 prevents customers from removing the last item in cart.

class-cocart-session-handler, line 427, will always return false since the cart is empty if removing the last item hence the cart won't save in the database.

Both in web / via the API call.

**Comment by seb86** [comment]
Thank you for reporting this bug @pauld8 

I have just pushed a change on the master branch which I hope will fix the issue. Mind checking it out for me please?

**Comment by pauld8** [comment]
Hi, this seems to have fixed the issue. I was able to remove the last item in cart.
