### ISSUE TITLE
ISBAT 

### ISSUE THREAD

**Issue by gawadepallavipratap** [co-cart/co-cart#191]
Hello,
I am facing 'Empty cart issue' with my website when I used cocart plugin for rest api in woocommerce.
I have used cocart 2.7.4 version plugin for rest api and all the rest api are working fine but it creates problem to my webiste view cart functionality.When I open cart it display Empty cart.
Please me with this.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [ ] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behaviour

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce and CoCart plugin are active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] This bug happens with the WordPress theme Storefront active.
- [ ] This bug happens with the latest release of WooCommerce active.
- [ ] This bug happens only when I authenticate as a customer.
- [ ] This bug happens only when I authenticate as administrator.
- [ ] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
```
Go to "WooCommerce > System Status then copy and paste the system status report here.
```
</details>

**Comment by seb86** [comment]
This report has no detailed information as requested in the template.
