### ISSUE TITLE
ISBAT ... Add multiple items to cart endpoint

### ISSUE THREAD

**Issue by jimishsoni1990** [co-cart/co-cart#195]
Can we have an endpoint like /add-items, to which we can pass the list of items we want to add to cart. 
There can be many events where we would like to add multiple items to cart. Currently i have to do that using a loop and make a call to /add-item endpoint for each item. I believe if i can add all the items in one API call, that will improve the performance of the app.

**Comment by seb86** [comment]
@jimishsoni1990 Thank you for your interest. A [batch add-on](https://cocart.xyz/add-ons/batch/) is currently in development.

Feel free to pre-order for early access once a beta is ready to test.
