### ISSUE TITLE
Getting cart with cart key always shows 0 products in cart

### ISSUE THREAD

**Issue by Jonofat** [co-cart/co-cart#222]
I am using this plugin along with CoCart - Get Cart Enhanced and I don't want to use cookies etc. So, when I add a product to the cart I see a key in the response that looks like this "76dc611d6ebaafc66cc0879c71b5db5c". So, that seems all good. But when I then try to get the cart it always shows 0 items. 

I am making a GET request like this:

```
  useEffect(() => {
    const getCart = async () => {
      const response = await axios.get(
        `http://localhost:8888/myshop/wp-json/cocart/v1/get-cart?cart_key=76dc611d6ebaafc66cc0879c71b5db5c`
      );
      console.log(response);
    };
    getCart();
  }, []);
```

What am I doing wrong?

**Comment by seb86** [comment]
Have you tested that CoCart functions first via one of the tools listed in the documentation? Also I provide a JS wrapper to fully support CoCart out the box.

**Comment by Jonofat** [comment]
Which tools are you referring to? I tried to get the X-CoCart-API in the header but I don't seem to be able to access it or see it using axios. If I try the below I don't see X-CoCart-API there. But if I look in my browser console I do see it there.

```
  const addToCartHandler = async () => {
    const response = await axios.post(
      `http://localhost:8888/myshop/wp-json/cocart/v1/add-item`,
      {
        product_id: "128",
        quantity: 1,
      }
    );
    console.log(response.headers);
  };
```

Also, could you please provide me with a link to the JS wrapper? If I can get the above sorted though then maybe I won't need it.

**Comment by seb86** [comment]
There is a lot in the documentation that already answers everything you need including [why the header is not returning](https://docs.cocart.xyz/#knowledge-base-why-am-i-not-seeing-the-x-cocart-api-header-returning).

You can search the documentation too to help narrow down the content.

I suggest looking a little harder please.

**Comment by Jonofat** [comment]
Apologies, I will take a look at that and if it works I will close this out.

**Comment by seb86** [comment]
Any updates @Jonofat

**Comment by Jonofat** [comment]
Sorry for delay. All sorted. I decided to go with Cookies and it is working nicely, thanks!

**Comment by seb86** [comment]
So was it a CORS issue?

**Comment by Jonofat** [comment]
Yes, after adding this filter it worked okay

`add_filter( 'cocart_disable_all_cors', function() { return false; });`
