### ISSUE TITLE
VAT checkout

### ISSUE THREAD

**Issue by sdevogel** [co-cart/co-cart#231]
Hi, i have a question about the VAT at checkout and how this is calculated. 
Since each country has different VAT rules, changing the shipping country should update the VAT. How would this be implemented? Also, when no country is selected yet, how is the VAT already calculated in the totals?

Thanks in advance,
sander

**Comment by seb86** [comment]
Checkout is not yet supported.

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review [https://cocart.xyz/support/](https://cocart.xyz/support/).

The easiest way to get support is to join us in the [`#support`](https://cocart.slack.com/messages/CMGGJP03U) channel via Slack for the [CoCart Community](https://cocart.xyz/community/).
