### ISSUE TITLE
Cache control

### ISSUE THREAD

**Issue by Maxh1989** [co-cart/co-cart#242]
Hey I'm just wondering I'm currently using the get-cart endpoint and running into problems with the Cache-Control. I need to be able to have the Cache-Control set to 0 so I can make the request quickly and wondering if that's an option?

**Comment by seb86** [comment]
@Maxh1989 Are you using any cache plugin?

**Comment by seb86** [comment]
Hope this commit helps. https://github.com/co-cart/co-cart/commit/abcfe106d480a863b7e6680688e2e713583f420f

Beta for v3.1 is near release for testing.

**Comment by Maxh1989** [comment]
Thanks so much!
