### ISSUE TITLE
Custom response after adding / removing a product from the cart

### ISSUE THREAD

**Issue by filuus** [co-cart/co-cart#253]
Is there any hook that I could modify the response I get after correctly adding / removing a product from the cart. I know I could use this hook `cocart_cart` but I would like to get different responses for the following endpoints:
`wp-json/cocart/v2/cart/add-item`
`wp-json/cocart/v2/cart/item/{item_key}`
`wp-json/cocart/v2/cart`

**Comment by seb86** [comment]
@filuus Please use the correct support channels for questions. The GitHub repository is for bug issues or enhancements only.

As for changing the response. API v2 was created based on a lot of feedback wanting the opposite of that. However, you can still change the response at the very end should you wish to do so. [See the response class](https://github.com/co-cart/co-cart/blob/master/includes/class-cocart-response.php#L52,#L58).
