### ISSUE TITLE
ISBAT merge carts from a guest to a registered customer.

### ISSUE THREAD

**Issue by seb86** [co-cart/co-cart#258]
Reports of late that this feature is not working. Need to re-test and see what is going wrong.

**Comment by seb86** [comment]
Bug demonstrated [in this video](https://screencast-o-matic.com/watch/crivIcViLPC).

According to Naeem in live support, it seems to be working only if the cookie for the guest cart is left alone. Should be working with or without cookie.

**Comment by seb86** [comment]
Can confirm that if no cookie exists prior to authenticating registered customer, the cart items from the guest cart does not merge.

**Comment by seb86** [comment]
[This commit](https://github.com/co-cart/co-cart/commit/10caa355c9dd44c7030763d8d5830be0a013323c) should help solve the issue.

**Comment by seb86** [comment]
That's so weird it's been working fine for me since the commit. Can you do a video for me please?

**Comment by naeemaly110** [comment]
yes here is the video url : https://screencast-o-matic.com/watch/crjXjJVjrH0

**Comment by seb86** [comment]
Just to confirm you are using JWT as authentication correct? I get reports half the time it doesn't work with JWT because of mis-configurations or the JWT plugin was badly coded but I think from what I am seeing, you are not using Postman correctly when authenticating.

There is a section designed for authentication alone which is what you should be using and from the video you have it set to "None" but add the authentication via the headers. This could be confusing the Postman app.

Try using the authentication section only not the headers for it. Hopefully you get the results you should be getting as I did with basic authentication.

**Comment by seb86** [comment]
P.S. I also disabled cookie tracking in Postman to test the fix and it worked without cookies too.
