### ISSUE TITLE
Login API request timeout on password error

### ISSUE THREAD

**Issue by cha0ran** [co-cart/co-cart#259]
The login API does not return an error when the password is wrong, but rather the request times out.

**Comment by seb86** [comment]
Any other details you can share @cha0ran ?

**Comment by cha0ran** [comment]
@seb86 
Ok, I made more attempts and when I entered an incorrect username, the interface returned a 401 error, but when I entered a correct username and an incorrect password, the interface generated a 504 timeout. And this seems to happen in all authentication sessions of the interface.

When the username is incorrect:
```
{
    "code": "cocart_rest_not_authorized",
    "message": "Sorry, you are not authorized.",
    "data": {
        "status": 401
    }
}
```

**Comment by seb86** [comment]
I did the same as you and all I get is the error you should be getting when doing basic authentication. 

```json
{
	"code": "cocart_authentication_error",
	"message": "Authentication is invalid.",
	"data": {
		"status": 401
	}
}
```

**Comment by seb86** [comment]
@cha0ran Maybe increase the timeout when authenticating.

**Comment by cha0ran** [comment]
Wow, that's a strange one then, looks like I need to double check that there are no problems elsewhere.

**Comment by cha0ran** [comment]
It seems that this problem disappeared after updating the plugin, which was previously used with version 3.0.10.
Thanks
