### ISSUE TITLE
[3.1 beta.1]: Co Cart White Label whilst calling Products V2 endpoint

### ISSUE THREAD

**Issue by BG-crafts** [co-cart/co-cart#262]
## <br />
<b>Warning</b>: Use of undefined constant COCART_WHITE_LABEL - assumed 'COCART_WHITE_LABEL' (this will throw an Error in
a future version of PHP) in
<b>/home/customer/www/bgcraft.co.uk/public_html/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart.php</b>
on line <b>230</b><br />

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [ ] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. Get https://bgcraft.co.uk/wp-json/cocart/v2/products
2. post with no authentication
3. Warning appears

## Expected/actual behaviour

should this happen?? 

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce and CoCart plugin are active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] This bug happens with the WordPress theme Storefront active.
- [ ] This bug happens with the latest release of WooCommerce active.
- [ ] This bug happens only when I authenticate as a customer.
- [ ] This bug happens only when I authenticate as administrator.
- [ ] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
```
Go to "WooCommerce > System Status then copy and paste the system status report here.
```
</details>

**Comment by seb86** [comment]
Already been fixed but thank you for reporting it.
