### ISSUE TITLE
[3.1 beta.2]: SiteGround Cache Issue

### ISSUE THREAD

**Issue by BG-crafts** [co-cart/co-cart#263]
## Describe the bug

headers already sent by (output started at /home/customer/www/bgcraft.co.uk/public_html/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart.php:230) in /home/customer/www/bgcraft.co.uk/public_html/wp-content/plugins/sg-cachepress/core/Supercacher/Supercacher_Helper.php on line 79

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [ x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. during Recaching of website, the Site ground cache threw a error
2.
3.

## Expected/actual behaviour

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x ] This bug happens with only WooCommerce and CoCart plugin are active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] This bug happens with the WordPress theme Storefront active.
- [x] This bug happens with the latest release of WooCommerce active.
- [ ] This bug happens only when I authenticate as a customer.
- [x ] This bug happens only when I authenticate as administrator.
- [ ] I can reproduce this bug consistently using the steps above.

## WordPress Environment

ultrafast php 7.421
Wordpress 5.8
```
Go to "WooCommerce > System Status then copy and paste the system status report here.
```
</details>

## Additional context

This only occured during recache so i am assuming it is do with the no cache response introduced??

**Comment by seb86** [comment]
@BG-crafts [Line 230](https://github.com/co-cart/co-cart/blob/v3.1.0-beta.2/includes/class-cocart.php#L230) for that file in CoCart doesn't make sense for it to trigger headers already sent. Have you contacted Siteground for any help on the matter?

I know that their version of PHP runs differently than regular PHP.

> This only occured during recache so i am assuming it is do with the no cache response introduced??

The [no cache response](https://github.com/co-cart/co-cart/blob/master/includes/class-cocart-rest-api.php#L423,#L430) that was recently added only affects the REST API not the WordPress dashboard.

Any additional context would be much appreciated.

**Comment by BG-crafts** [comment]
this looks like .htaccess issue, all the API links went down completely couldn't get them back up after full cache flushes and permalinks refresh. 

Had to go back to a previous backup to understand the changes here will let you know if i find anything

**Comment by seb86** [comment]
Any updates on this issue @BG-crafts ?

**Comment by seb86** [comment]
Closing issue.
