### ISSUE TITLE
3.0.16 Remove Item is failing for some valid cart ids

### ISSUE THREAD

**Issue by rozalia** [co-cart/co-cart#287]
## Describe the bug

The `remove_item()` method in `CoCart_Remove_Item_v2_Controller` has a wired condition:

```php
if ( 0 === $item_key || $item_key < 1 ) {
    $message = __( 'Cart item key is required!', 'cart-rest-api-for-woocommerce' );
    ...
}
```

This will evaluate to `true` for some valid item keys.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. Try with item key like `e60f98971bfb5bc6564315ef7c69ec84`
2. PHP evaluates  `$item_key < 1` as `true`
3. The whole condition is evaluated to `true` and the `Cart item key is required!` exception is being raised: 
```js
{
    "code": "cocart_cart_item_key_required",
    "message": "Cart item key is required!",
    "data": {
        "status": 404
    }
}
```

## Expected/actual behaviour

Valid item keys should be allowed to be removed.

## Isolating the problem

- [x] This bug happens with only WooCommerce and CoCart plugin are active.
- [x] This bug happens with a default WordPress theme active.
- [x] This bug happens with the WordPress theme Storefront active.
- [x] This bug happens with the latest release of WooCommerce active.
- [x] This bug happens only when I authenticate as a customer.
- [ ] This bug happens only when I authenticate as administrator.
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
```

WordPress 5.8.2

WooCommerce 5.9.0

PHP 7.4

```
</details>

**Comment by seb86** [comment]
Thank you for reporting the bug @rozalia I will run some tests and maybe undo the statement change in the last plugin update.

**Comment by fatheaddrummer** [comment]
The same issue occurs on the cart item update controller, which makes it impossible to update or remove cart items currently.

**Comment by seb86** [comment]
@fatheaddrummer @rozalia Please roll back CoCart to the last stable release v3.0.15. A new patch is in the works. Thank you.

**Comment by fatheaddrummer** [comment]
@seb86 Thank you!

**Comment by seb86** [comment]
@rozalia May I have your WordPress dot org profile so that I can credit you for your contribution?

**Comment by rozalia** [comment]
Hey @seb86 thank you for your quick response, this is my Wordpress.org profile url https://profiles.wordpress.org/rozaliastoilova/

**Comment by seb86** [comment]
Thank you @rozalia 

Update will be posted on [CoCart.dev/news/](https://cocart.dev/news/)

**Comment by seb86** [comment]
Hey @rozalia A new release candidate is now available for testing. Details here: https://cocart.dev/cocart-lite-v3-0-17-release-candidate-1/
