### ISSUE TITLE
Custom Cart Item Data not returned, when added to cart

### ISSUE THREAD

**Issue by fatheaddrummer** [co-cart/co-cart#288]
## Describe the bug

When I add an item to cart with custom `item_data` and set `return_item` to true, the cart Item is returned, but `cart_item_data` is empty. When the cartItem is fetched (`wp-json/cocart/v2/cart/items`), the `cart_item_data` property is returned correctly.

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest `master` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [x ] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. Submit an add-to-cart request

[POST] `wp-json/cocart/v2/cart/add-item`
```
{
	"id":"<simple_product_id>",
	"return_item":true,
	"item_data": {
		"my_test_data":"my-test-value"
	}
}

```
2. Check the response: `cart_item_data` property is empty
3. Fetch the item via `wp-json/cocart/v2/cart/items`: `cart_item_data` is correct

## Expected/actual behaviour

`cart_item_data` should be retunred with values after the add to cart request.

## Isolating the problem

- [ x] This bug happens with only WooCommerce and CoCart plugin are active.
- [ x] This bug happens with a default WordPress theme active.
- [ ] This bug happens with the WordPress theme Storefront active.
- [x ] This bug happens with the latest release of WooCommerce active.
- [ ] This bug happens only when I authenticate as a customer.
- [ ] This bug happens only when I authenticate as administrator.
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by seb86** [comment]
@fatheaddrummer I have confirmed the bug and will look into it further.

**Comment by fatheaddrummer** [comment]
@seb86 Awesome, thank you very much!

**Comment by seb86** [comment]
@fatheaddrummer Issue has been fixed and will be available in the next release. May I have your name and WordPress dot org profile so that I can credit your for your contribution.

**Comment by seb86** [comment]
Hey @fatheaddrummer A new release candidate is now available for testing. Details here: https://cocart.dev/cocart-lite-v3-0-17-release-candidate-1/
