### ISSUE TITLE
add_to_cart request filter

### ISSUE THREAD

**Issue by qstudio** [co-cart/co-cart#289]
when adding items to the cart, the filter on the Request object is run after the ID, quantity, variation & item_data is taken and filtering these items has no effect.

Our use case requires that products are passed as a hash, and then we would want to filter the request to translate the passed product hash into the product ID.

This could be achieved simply be re-ordering the filter location, so that it comes above the variable setting, like so:

```php
/**
	 * Add to Cart.
	 *
	 * @throws  CoCart_Data_Exception Exception if invalid data is detected.
	 *
	 * @access  public
	 * @since   1.0.0
	 * @version 3.0.0
	 * @param   WP_REST_Request $request Full details about the request.
	 * @return  WP_REST_Response
	 */
	public function add_to_cart( $request = array() ) {
		try {

			$controller = new CoCart_Cart_V2_Controller();

			// Filters additional requested data.
			$request = $controller->filter_request_data( $request );

			$product_id = ! isset( $request['id'] ) ? 0 : wc_clean( wp_unslash( $request['id'] ) );
			$quantity   = ! isset( $request['quantity'] ) ? 1 : wc_clean( wp_unslash( $request['quantity'] ) );
			$variation  = ! isset( $request['variation'] ) ? array() : $request['variation'];
			$item_data  = ! isset( $request['item_data'] ) ? array() : $request['item_data'];

``` 

This way, the request object can be filtered correctly using the $request->get_params() & $request->set_params() methods.

**Comment by seb86** [comment]
@qstudio The point of adding the filter after was so that the main parameters are not altered before to prevent issues. Why are the products passed as a hash?

**Comment by qstudio** [comment]
we sell products which require specific consultations to be completed before they can be purchased and we also pull all product data from a centralized API, in both cases hashes allow us to related child products to the parent product and avoid people adding items to their carts which they are not allowed to purchase.

But, in any case, I don't see the point of a filter which does not allow you to alter the main endpoint params, the WC add to cart method allowed the params to be filtered via the rest_request_before_callbacks filter, perhaps this will also work with Cocart, I did not try yet.

**Comment by qstudio** [comment]
If people use filters incorrectly, for example in a way that corrupts the request object params, the logical part of the endpoint, such as the part that validates if the product ID is correct and valid, will capture the error and reject the request - that is the same risk applied to any filter inside WP, but also part of what makes it a flexible system!

**Comment by qstudio** [comment]
Just to confirm that I can achieve the same result using a standard WP REST API filter `rest_request_before_callbacks`
