### ISSUE TITLE
CoCart 3.1.2 Review nag is not dismissable 

### ISSUE THREAD

**Issue by maketheboat** [co-cart/co-cart#322]
The nag at the top of the page always returns, no matter how many times it is dismissed - this is the second such nag issue - however there was a filter the remove previous notices, this one seems to have no filter to control it.

Install version 3.1.2 and visit an admin page.

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `trunk` branch of CoCart on GitHub.
- [x] The issue still exists against the latest `dev` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional)
- [X] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1.Install version 3.1.2 and visit an admin page.

## Expected/actual behavior

Click dismiss and the notice does not show again

When I follow those steps, I see...

No more notice

## Screenshots

](https://ibb.co/3MhrYwL)

## Isolating the problem

- [x] This bug happens with only WooCommerce and CoCart plugin are active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] This bug happens with the WordPress theme Storefront active.
- [ ] This bug happens with the latest release of WooCommerce active.
- [ ] This bug happens only when I authenticate as a customer.
- [ ] This bug happens only when I authenticate as administrator.
- [ ] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
```
Go to "WooCommerce > System Status then copy and paste the system status report here.
```
</details>

**Comment by seb86** [comment]
@qstudio It probably doesn't believe you left a review. LOL 

No, seriously I will look into the issue. Thank you for reporting it.

**Comment by maketheboat** [comment]
I'll surely leave a great review, once you fix this ;) Of course, seriously, thanks for the great plugins, it plugs a huge gap in WC!

**Comment by seb86** [comment]
Can confirm that the dismiss action is saving a value under the `wp_usermeta` table but it's still being ignored on the next page load. 🤔

**Comment by maketheboat** [comment]
A short term fix is to disable all nags with a global filter:

```\add_filter( 'cocart_show_admin_notice', function(){ return false; } );```

**Comment by seb86** [comment]
Issue is now fixed and will be pushed with the next update.

**Comment by maketheboat** [comment]
Great - thanks!
