### ISSUE TITLE
Cart not updating when removing the product and having cocart-load-cart param in URL

### ISSUE THREAD

**Issue by luco** [co-cart/co-cart#324]
I'm using the version 3.2.0 from the trunk. When the `cocart-load-cart` key is set on URL and I try to remove a product from the cart, it doesn't remove. The ajax refreshes and keeps the product. 

When I remove the param from the URL and remove, it works.

**Comment by seb86** [comment]
Hi @luco 

I have not been able to replicate the issue. Items remove fine and I can restore without removing the `cocart-load-cart` parameter.

**Comment by seb86** [comment]
I was logged out so the cart was loaded as a guest as it's designed. I'm assuming your logged in.

**Comment by luco** [comment]
Yes. What it's the best way to handle a user that's logged and not logged?

**Comment by seb86** [comment]
Well, the feature wasn't designed for registered customers. The idea is that if you are bringing back a returning customer to the native checkout they would need to log in to continue.

Open to suggestions on how to do this safely without conflict.

**Comment by luco** [comment]
What about clearing the cart for logged users?

**Comment by seb86** [comment]
Well that wouldn't work because your removing items the customer may want that was saved before.

**Comment by luco** [comment]
Yeah, but a flag would be great, like `clear-cart=true` to explicity clear it. Or maybe merge the cart.

**Comment by seb86** [comment]
I will see what I can do.

**Comment by luco** [comment]
Thanks a lot @seb86!

**Comment by seb86** [comment]
@luco Have you tried setting `keep-cart` to false?

Example: `https://example.com/cart/?cocart-load-cart=bbfa8e97ac9cff4c861d62a109e83bb6&keep-cart=0`

**Comment by luco** [comment]
@seb86 In fact it works, but the problem comes again to the logged user that, once goes to cart, can't remove the product as I described in the issue. This only happens if the used is logged in.

**Comment by seb86** [comment]
@luco I'm afraid that it's only an issue with the vendors plugin and I don't currently have the resources to solve it. Perhaps you can get further assistance from the vendor plugin developers.

**Comment by seb86** [comment]
Closing this issue.
