### ISSUE TITLE
Clearing the cart should return an empty array

### ISSUE THREAD

**Issue by joshuaiz** [co-cart/co-cart#33]
First, this is great plugin so thank you!

I'm having issues with the Clear Cart endpoint: in a React app, it is quite common to have to filter an array to update state and/or send props to child components from a filtered/mapped array.

When you use the `clear` endpoint, it returns the string "Cart is empty!" which makes it really difficult to fully clear the cart. When I removed the string from the plugin in `class-wc-rest-cart-controller.php` at line 167, everything works as normal: I can clear the cart update my state to: `cart: []`.

Without removing the string, if I reload, since I'm filtering the cart to an array using map and `Object.values`, it will return the 'Cart is empty!' string as indexed letters in the array, e.g. `0: "C", 1: "a", 2: "r", 3: "t",...

Is the 'Cart is empty!' string really necessary? It should be easy enough to add whatever 'Empty cart' message you may need on the client side and ideally when the cart is cleared it should return an empty array, not a string.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Cart REST-API for WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. Use the `clear` endpoint to clear the cart
2. Update React application state (e.g. state= { cart: [] }
3. Reload.
4. Cart is not empty; includes 'Cart is empty!' string; would fail boolean or length test

## Expected/actual behaviour

Using the `clear` endpoint should return an empty array.

## Isolating the problem

- [x] This bug happens with only WooCommerce and Cart REST-API for WooCommerce plugin are active.
- [x] This bug happens with a default WordPress theme active.
- [x] This bug happens with the WordPress theme Storefront active.
- [x] This bug happens with the latest release of WooCommerce active.
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
```
Go to "WooCommerce > System Status then copy and paste the system status report here.
```
</details>

**Comment by seb86** [comment]
@joshuaiz I will look into this.

**Comment by seb86** [comment]
Hi @joshuaiz 

Right now on line [#L223](https://github.com/seb86/cart-rest-api-for-woocommerce/blob/master/includes/api/class-wc-rest-cart-controller.php#L223) it returns this response: `return new WP_REST_Response( __( 'Cart is cleared.', 'cart-rest-api-for-woocommerce' ), 200 );`

This is the normal way to return a successful response for the REST-API, however, due to code formatting issues you are experiencing. Would this response be better?

```
return array(
	'wc_cart_rest_clear_cart_successful' => __( 'Cart is cleared.', 'cart-rest-api-for-woocommerce' ),
	'status' => 200
);
```

It's not an empty or error response but would be a better way to validate that the cart was successfully cleared. Please let me know what you think.

Thank you.

**Comment by joshuaiz** [comment]
Hi @seb86,

Again, thanks for all your work on this plugin.

That seems like it would work. How would that response be returned from the API call?

Just as an example, here is what I am using now in my `addToCart()` function to check if the cart is empty:

```javascript
if (this.state.cart.length === 14) {
    const currentCart = []
    this.setState({
        cart: [...currentCart, cartResponse.data]
    })
}
```

^^ The '14' is the length of the string 'Cart is empty!' so if the cart is that length, clear it to an empty array. It's definitely a bit hacky, but it is working right now.

Maybe mine is an edge case but I'd want to be able to check if the actual cart is an empty array and have the response string returned a different way vs. in the cart itself. If that is what your change does, then great!!

**Comment by seb86** [comment]
I have not tested it yet but the suggested change I made would return something like this:

```
{
	'wc_cart_rest_clear_cart_successful':'Cart is cleared.',
	'status':200
}
```
and I just realized it needs to be encoded in json format which is what the normal REST-API response does for me.

so it should return like so to give you the returned result above:

```
return json_encode( array(
	'wc_cart_rest_clear_cart_successful' => __( 'Cart is cleared.', 'cart-rest-api-for-woocommerce' ),
	'status' => 200
) );
```

Just out of curiosity @joshuaiz, why do you need to check if the cart is empty before adding an item?

**Comment by joshuaiz** [comment]
Hi @seb86,

If there is already a product in the cart, then in React you can just merge a new item into the cart array using the spread operator.

But if it is 'empty' currently, the cart still has the 'Cart is empty!' _string_ so you can't merge a new product into it as an array — React (or javascript) doesn't like that too much.

Thus, I need to check if it is actually an empty array first, then I can add my product to the cart array.

Does that make sense?

**Comment by seb86** [comment]
Yes.

**Comment by yaundanns** [comment]
how cocart handle the cart? is it session cart? i have got an empty cart after i have sucessfully added some product to the cart?

**Comment by DennisMatise** [comment]
@joshuaiz The current response is always the same and is including an 200 status and also a message. You can create a function that checks on the response.status and a double check with a regex if the response.data is including an clear string. If this is true you can just use:

```js
this.setState({
	cart: []
})
```
This is how I use it in my project

**Comment by seb86** [comment]
@joshuaiz I have applied the change to the master branch. Before I release this to the public, could test the master branch and let me know if this works better for you. I went with returning nothing for easy development and compatibility as requested.

**Comment by joshuaiz** [comment]
@seb86 cool Seb! Give me a few days to check it out. Thanks for updating this!
