### ISSUE TITLE
JWT Authentication not working anymore.

### ISSUE THREAD

**Issue by rjdeveloper007** [co-cart/co-cart#357]
Hello,

I was using JWT Authentication from long time with CoCart for cart authentication and it was working fine but suddenly it stopped working and starts showing invalid_username error. Please check error which I am getting:

```json
{
    "code": "invalid_username",
    "message": "<strong>Error</strong>: The username <strong>{\"typ\"</strong> is not registered on this site. If you are unsure of your username, try your email address instead.",
    "data": null
}
```

I have successfully get token (jwt-auth/v1/token) by calling this endpoint and when I am passing that token with get cocart/v2/cart endpoint its giving above error.

Please check attached screenshot.

![cocart-token-auth-not-working](https://user-images.githubusercontent.com/115626320/195312247-3fa09e96-aa8b-4609-99ca-2f52086071d0.png)

**Comment by seb86** [comment]
@rjdeveloper007 The answer is in the error response. **The username doesn't exist.**

What am I missing here because there hasn't been any updates that affect JWT?

**Comment by seb86** [comment]
This plugin is closed now which is news to me. https://wordpress.org/plugins/jwt-auth/

**Comment by rjdeveloper007** [comment]
@seb86 

Thanks for quick replying and yes this plugin is closed now.  I have figured out the issue for now.

If anyone facing same issue then downgrade the plugin to one lower version. Don't use latest version of JWT-auth which is causing issue. Better would be go with some other auth plugin.

**Comment by seb86** [comment]
If you have another JWT plugin you can recommend with CoCart. Please let me know. Thank you.
