### ISSUE TITLE
There is no way to apply taxes and coupons with CoCart Cart while frontend cart/checkout page.

### ISSUE THREAD

**Issue by rjdeveloper007** [co-cart/co-cart#359]
Hi,

Can you please let me know how can I apply taxes and coupon on cocart cart. Currently I have to manually calculate that part and it is causing many issue like invalid subtotal on frontend and backend. You have made fully headless plugin so I am sure there must be a way to do that in your cocart api or maybe in pro plugin. So can you please suggest on how can I handle taxes and coupon with cocart api inside of manually.

 Taxes ==>  How taxes will apply with a cart. I didn't find any way to add billing country and state information while adding items to CoCart. I have tried to add billing info using item_data but it doesn't seem to be working. 

Can you please suggest how taxes work with CoCart API.  I have set up a standard tax for country US and state CA which is 9.5% for e.g. So how can I get the tax amount applied on CoCart cart total amount.

Coupon ==> How can I apply coupon to cocart cart using cocart API. SO that I don't have to do manually calculation.

Please let me know if this are the PRO feature. Looking forward your reply.

**Comment by rjdeveloper007** [comment]
Hello Sir,

1). Coupon :  I know you have mention of coupons API in PRO version but just want to confirm on this.
2). Tax : There is no information for tax API in both free and pro version of COCart documentation and which is biggest issue for me which I can think. Because of manually calculations we are getting different price amount on both frontend and backedn.

Can you please guide me on tax API. I am sure you are also aware of this and I hope there is a way of applying taxes on CoCart Cart.

Looking forward for your reply!

**Comment by seb86** [comment]
Sorry for the late response. If you wanted answers for pre-sale questions asap you should have used the contact form via the website.

1. Coupons is supported in CoCart Pro.
2. The Tax is currently only supported once a shipping method has been applied. I'm currently working on a new core update that will allow me to complete additional features.

**Comment by rjdeveloper007** [comment]
@seb86 

I have purchased CoCart PRO version and seems like tax added automatically with shipping methods API.
