### ISSUE TITLE
Guest users cart is cleared when increasing quantity from the cart.

### ISSUE THREAD

**Issue by abhishekfornoesis** [co-cart/co-cart#365]
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

So on the website for non-logged-in users, when we add products to the cart and, increase the quantity then the cart is getting cleared.

### Expected behavior

For website it works normally if logged in and for mobile application to also works.

### Actual behavior

For website non logged in users are not able to add products to cart and same happened on the mobile also.

### Steps to reproduce

1. Activate CoCart plugin and CoCart Pro plugin.
2. Then go to the website as a non-logged-in user and add a product to cart.
3. Increase quantity from the cart. 
4. Cart gets cleared.

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://hyugalife-wp.pratech.dev
Site address (URL): https://hyugalife-wp.pratech.dev
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.5.2
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 8.1.2-1ubuntu2.8
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.28
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: wp_
Total Database Size: 386.07MB
Database Data Size: 255.24MB
Database Index Size: 130.83MB
wp_woocommerce_sessions: Data: 4.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.17MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.80MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ac_segments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 12.02MB + Index: 13.00MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 10.02MB + Index: 7.03MB + Engine InnoDB
wp_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_braapf_product_stock_status_parent: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
wp_braapf_product_variation_attributes: Data: 0.14MB + Index: 0.25MB + Engine InnoDB
wp_braapf_term_taxonomy_hierarchical: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_braapf_variable_attributes: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_cocart_carts: Data: 0.19MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.39MB + Index: 0.36MB + Engine InnoDB
wp_fsmpt_email_logs: Data: 9.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_imagify_files: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mo_openid_linked_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nks_wishlist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 17.23MB + Index: 2.14MB + Engine InnoDB
wp_pmxe_exports: Data: 2.50MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 13.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 97.63MB + Index: 43.16MB + Engine InnoDB
wp_posts: Data: 38.39MB + Index: 10.00MB + Engine InnoDB
wp_relevanssi: Data: 25.58MB + Index: 39.97MB + Engine InnoDB
wp_relevanssi_log: Data: 3.52MB + Index: 3.52MB + Engine InnoDB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 2.47MB + Index: 1.42MB + Engine InnoDB
wp_term_taxonomy: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_termmeta: Data: 0.17MB + Index: 0.28MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 2.52MB + Index: 3.00MB + Engine InnoDB
wp_users: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 1.50MB + Index: 1.27MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.52MB + Index: 0.95MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 0.52MB + Index: 0.66MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 82
acf-field-group: 10
attachment: 51196
br_filters_group: 2
br_product_filter: 17
mailpoet_page: 1
nav_menu_item: 87
page: 26
post: 271
product: 3114
product_variation: 1198
revision: 228
shop_coupon: 14
shop_order: 580
shop_order_refund: 2
testimonial: 7
web-story: 163
wp_global_styles: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

Admin Columns Pro - WooCommerce: by AdminColumns.com – 3.7.3
Advanced Custom Fields: Options Page: by Elliot Condon – 2.1.0
Advanced Custom Fields: Repeater Field: by Elliot Condon – 2.1.0
Admin Columns Pro: by AdminColumns.com – 5.7.4
Advanced Cron Manager: by BracketSpace – 2.4.2
Advanced Custom Fields PRO: by WP Engine – 6.0.4
Better Search Replace: by Delicious Brains – 1.4.1
CoCart - Headless ecommerce: by Sébastien Dumont – 3.7.9
Classic Editor: by WordPress Contributors – 1.6.2
CoCart - Cart Enhanced: by Sébastien Dumont – 3.2.0
CoCart Pro: by Sébastien Dumont – 1.0.0-rc.5
Custom Endpoints: by Noesis Knowlegde Solution Pvt. Ltd. – 1.0
Disable REST API and Require JWT / OAuth Authentication: by Benjamin Intal
Gambit Technologies
Inc. – 1.0

Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Facebook for WooCommerce: by Facebook – 2.6.30
FluentSMTP: by FluentSMTP & WPManageNinja Team – 2.2.2
Imagify: by Imagify - Optimize Images & Convert WebP – 2.0
JWT Authentication for WP-API: by Enrique Chavez – 1.3.2
Social Login, Social Sharing by miniOrange: by <a href="https://www.miniorange.com/">miniOrange</a> – 7.5.14
Relevanssi Live Ajax Search: by Mikko Saari – 2.1
Relevanssi: by Mikko Saari – 4.18.0
Theme My Login: by Theme My Login – 7.1.5
User Switching: by John Blackbourn & contributors – 1.7.0
WC Variations Radio Buttons: by 8manos – 2.0.5
Web Stories: by Google – 1.27.0
WP Sheet Editor - WooCommerce Products: by WP Sheet Editor – 1.7.21
Variation Images Gallery for WooCommerce: by RadiusTheme – 2.2.3
Razorpay for WooCommerce: by Team Razorpay – 4.3.4
Advanced AJAX Product Filters for WooCommerce: by BeRocket – 1.6.3.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.17
Woocommerce Side Cart Premium: by XootiX – 3.1
WooCommerce: by Automattic – 7.1.0
WP All Import Pro: by Soflyy – 4.7.8
Asset CleanUp: Page Speed Booster: by Gabe Livan – 1.3.8.9
WP Crontrol: by John Blackbourn & crontributors – 1.14.0
WP-REST-API V2 Menus: by Claudio La Barbera – 0.12.1
WP Rocket: by WP Media – 3.12.2.1
WP All Import - ACF Add-On: by Soflyy – 3.3.8
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 3.3.4
YITH WooCommerce Wishlist: by YITH – 3.14.0

### Inactive Plugins (10) ###

CoCart - Advanced Custom Fields: by Sébastien Dumont – 1.0.0-rc.1
Colorlib Login Customizer: by Colorlib – 1.3.1
Login as User: by Web357 – 1.4.4
Side Cart WooCommerce: by XootiX – 2.1
Theme My Login Redirection: by Theme My Login – 1.1
Theme My Login Social: by Theme My Login – 1.1
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.5
WP All Export Pro: by Soflyy – 1.7.8
WP Rocket | Cache WP Rest API: by WP Rocket Support Team –
WP Rocket | Force Page Caching: by WP Rocket Support Team –

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔

### WC Pages ###

Shop base: #40 - /shop/
Cart: #41 - /cart/
Checkout: #42 - /checkout/
My account: #43 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: hyugaa
Version: 1.0.2
Author URL: http://underscores.me/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: hyugaa/woocommerce/archive-product.php
hyugaa/woocommerce/checkout/cart-errors.php
hyugaa/woocommerce/checkout/form-billing.php
hyugaa/woocommerce/checkout/form-checkout.php
hyugaa/woocommerce/checkout/form-coupon.php version 3.4.4 is out of date. The core version is 7.0.1
hyugaa/woocommerce/checkout/form-login.php
hyugaa/woocommerce/checkout/form-pay.php version 5.2.0 is out of date. The core version is 7.0.1
hyugaa/woocommerce/checkout/form-shipping.php
hyugaa/woocommerce/checkout/order-receipt.php
hyugaa/woocommerce/checkout/payment-method.php
hyugaa/woocommerce/checkout/payment.php version 3.5.3 is out of date. The core version is 7.0.1
hyugaa/woocommerce/checkout/review-order.php
hyugaa/woocommerce/checkout/terms.php
hyugaa/woocommerce/checkout/thankyou.php
hyugaa/woocommerce/content-single-product.php
hyugaa/woocommerce/global/breadcrumb.php
hyugaa/woocommerce/loop/add-to-cart.php
hyugaa/woocommerce/loop/loop-end.php
hyugaa/woocommerce/loop/loop-start.php
hyugaa/woocommerce/myaccount/dashboard.php
hyugaa/woocommerce/myaccount/downloads.php
hyugaa/woocommerce/myaccount/form-add-payment-method.php version 4.3.0 is out of date. The core version is 7.0.1
hyugaa/woocommerce/myaccount/form-edit-account.php version 3.5.0 is out of date. The core version is 7.0.1
hyugaa/woocommerce/myaccount/form-edit-address.php version 3.6.0 is out of date. The core version is 7.0.1
hyugaa/woocommerce/myaccount/form-login.php version 4.1.0 is out of date. The core version is 7.0.1
hyugaa/woocommerce/myaccount/form-lost-password.php version 3.5.2 is out of date. The core version is 7.0.1
hyugaa/woocommerce/myaccount/form-reset-password.php version 3.5.5 is out of date. The core version is 7.0.1
hyugaa/woocommerce/myaccount/lost-password-confirmation.php
hyugaa/woocommerce/myaccount/my-account.php
hyugaa/woocommerce/myaccount/my-address.php
hyugaa/woocommerce/myaccount/my-downloads.php
hyugaa/woocommerce/myaccount/my-orders.php
hyugaa/woocommerce/myaccount/navigation.php
hyugaa/woocommerce/myaccount/orders.php version 3.7.0 is out of date. The core version is 7.0.1
hyugaa/woocommerce/myaccount/payment-methods.php
hyugaa/woocommerce/myaccount/view-order.php
hyugaa/woocommerce/order/form-tracking.php version 6.5.0 is out of date. The core version is 7.0.1
hyugaa/woocommerce/order/order-again.php
hyugaa/woocommerce/order/order-details-customer.php
hyugaa/woocommerce/order/order-details-item.php
hyugaa/woocommerce/order/order-details.php
hyugaa/woocommerce/order/order-downloads.php
hyugaa/woocommerce/order/tracking.php
hyugaa/woocommerce/product-searchform.php version 3.3.0 is out of date. The core version is 7.0.1
hyugaa/woocommerce/single-product/add-to-cart/external.php version 3.4.0 is out of date. The core version is 7.0.1
hyugaa/woocommerce/single-product/add-to-cart/grouped.php version 4.8.0 is out of date. The core version is 7.0.1
hyugaa/woocommerce/single-product/add-to-cart/simple.php version 3.4.0 is out of date. The core version is 7.0.1
hyugaa/woocommerce/single-product/add-to-cart/variable.php
hyugaa/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 3.4.0 is out of date. The core version is 7.0.1
hyugaa/woocommerce/single-product/add-to-cart/variation.php
hyugaa/woocommerce/single-product/meta.php
hyugaa/woocommerce/single-product/photoswipe.php
hyugaa/woocommerce/single-product/price.php
hyugaa/woocommerce/single-product/product-attributes.php
/var/www/hyugalife/wp-content/plugins/woo-product-variation-gallery/templates/product-images.php
/var/www/hyugalife/wp-content/plugins/woo-product-variation-gallery/templates/product-thumbnails.php
hyugaa/woocommerce/single-product/rating.php
hyugaa/woocommerce/single-product/related.php
hyugaa/woocommerce/single-product/review-meta.php
hyugaa/woocommerce/single-product/review-rating.php
hyugaa/woocommerce/single-product/review.php
hyugaa/woocommerce/single-product/sale-flash.php
hyugaa/woocommerce/single-product/share.php
hyugaa/woocommerce/single-product/short-description.php
hyugaa/woocommerce/single-product/stock.php
hyugaa/woocommerce/single-product/tabs/additional-information.php
hyugaa/woocommerce/single-product/tabs/description.php
hyugaa/woocommerce/single-product/tabs/tabs.php
hyugaa/woocommerce/single-product/title.php
hyugaa/woocommerce/single-product/up-sells.php
hyugaa/woocommerce/single-product-reviews.php
hyugaa/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-24 06:25:07 +05:30
Options: ✔
Notes: 61
Onboarding: completed

### Action Scheduler ###

Complete: 25,662
Oldest: 2022-11-23 16:46:49 +0000
Newest: 2022-11-23 16:53:03 +0000

Failed: 1,556
Oldest: 2022-11-01 03:57:19 +0000
Newest: 2022-11-23 08:00:06 +0000

Pending: 5
Oldest: 2022-11-23 16:53:07 +0000
Newest: 2022-11-24 08:00:06 +0000

### CoCart ###

Version: 3.7.9
Database Version: 3.7.9
Install Date: November 16
2022

Carts in Session: 35
Carts Active: 35 out of 35 in session.
Carts Expiring Soon: 0 out of 35 in session.
Carts Expired: 0 out of 35 in session.
Carts Source (by CoCart): 19
Carts Source (by Web): 13
Carts Source (by Other): 3

### Status report information ###

Generated at: 2022-11-23 22:23:36 +05:30
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only CoCart plugin is active.
- [X] I can reproduce this bug consistently using the steps above.

**Comment by seb86** [comment]
Not been able to replicate this. Any updates @abhishekfornoesis ?
