### ISSUE TITLE
Handling WC Notices

### ISSUE THREAD

**Issue by njbotkin** [co-cart/co-cart#38]
Thanks for the plugin!  I'm working on implementing coupon endpoints, and I've noticed that cart-rest-api-for-woocommerce ignores WooCommerce notices (as far as I can tell).

Here's roughly how notices work: anytime WC wants to show the user a message it adds it to an array stored in `WC()->session`.  Next time a page is rendered the queued notices are emptied onto the page.  But the Cart API doesn't ever empty notices, so throughout usage, notices build up on the server.  

Since the status handling on coupon actions isn't handled very nicely by WooCommerce, in order to send back a status such as "Coupon code already applied!", I need to send notices back with the request.  Right now I'm sending back a diff of the notices from the start of the method with the notices at the end of the method.  Theoretically, this means I'm only sending back the notice(s) that the request generated.

In general, how do you think this should be handled?  It seems to me that we should send notices back with the API requests that generate them, and clear the notice queue.

Thanks!

**Comment by seb86** [comment]
@njbotkin How would do you see the notices returned? Don't forget this API has to support different languages that could be used to build a custom app.

**Comment by seb86** [comment]
@njbotkin Thank you for sharing but I don't think that is the approach we are looking for.
