### ISSUE TITLE
Updating a cart or removing an item from a cart add random products to the cart

### ISSUE THREAD

**Issue by bilalimran1412** [co-cart/co-cart#383]
![image](https://github.com/co-cart/co-cart/assets/29264592/a9fbb1ec-bbb8-41b6-83e6-46360fb413e9)

**Comment by seb86** [comment]
Closing issue due to insufficient information. Please [report using the appropriate template](https://github.com/co-cart/co-cart/issues/new?assignees=&labels=&projects=&template=1-bug-report.yml) and provide what is requested.
