### ISSUE TITLE
problem with multiple reqs in a row

### ISSUE THREAD

**Issue by sinavali** [co-cart/co-cart#384]
i have a if statement in my code that will filter some cart items and after that it will create for loop to get all item_key(s) and send them to remove item api.
the problem is, when requests have been sent and resolved the responses, everything in the responses are good, but after that when i send GetCart request, the products (mines the last one) are still in the cart. so for 3 remove_from_cart req, only one (last) will remove...
this problem can be resolved if there was an api to bulk remove items from cart.

thanks in advance

**Comment by seb86** [comment]
@sinavali Sounds like the session didn't save changes made in time before the next request to remove another item was processed. Bulk requests is coming in the next big update if feedback on the beta goes well.
