### ISSUE TITLE
Add to cart POST is missing cart item data check

### ISSUE THREAD

**Issue by DennisMatise** [co-cart/co-cart#41]
On line 102 of the `class-wc-rest-cart-controller` file the cart_item_data (also the variation on line 99) is blocking the request. 'is_array' won't be recognized as a valid function. To solve this we can create our own function.

```php
<?php
register_rest_route( $this->namespace, '/' . $this->rest_base . '/add', array(
	'methods'  => WP_REST_Server::CREATABLE,
	'callback' => array( $this, 'add_to_cart' ),
	'args'     => array(
		'product_id' => array(
			'validate_callback' => function( $param ) {
				return is_numeric( $param );
			}
		),
		'quantity' => array(
			'validate_callback' => function( $param ) {
				return is_numeric( $param );
			}
		),
		'variation_id' => array(
			'validate_callback' => function( $param ) {
				return is_numeric( $param );
			}
		),
		'variation' => array(
			'validate_callback' => function( $param ) {
				return is_array( $param );
			}
		),
		'cart_item_data' => array(
			'validate_callback' => function( $param ) {
				return is_array( $param );
			}
		)
	)
) );
?>
```

This will allow me to add custom data to my cart. I'll create a PR after this issue.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Cart REST-API for WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. Create a POST to cart/add
2. Add a param with the key `cart_item_data` (array is accepted according to the docs)

## Expected/actual behaviour

If you follow these steps you will result in an error: `error: 400, Invalid parameter(s):`
It should return the product added to the cart instead.

If we use the solution I described the expected outcome will return including the extra data. 

## Isolating the problem

- [x] This bug happens with only WooCommerce and Cart REST-API for WooCommerce plugin are active.
- [x] This bug happens with a default WordPress theme active.
- [x] This bug happens with the WordPress theme Storefront active.
- [x] This bug happens with the latest release of WooCommerce active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by seb86** [comment]
PR Merged.
