### ISSUE TITLE
Access-Control-Allow-Credentials being outputted as 1 instead of 'true'

### ISSUE THREAD

**Issue by SebastianLamprecht** [co-cart/co-cart#410]
## Describe the bug
When trying to fetch cart data with axios on my headless WooCommerce store, I encountered an CORS error, which I eventually tracked down to the Access-Control-Allow-Credentials header being set to 1. I located the piece of code inside the class-cocart-authentication.php and exchanged the boolean true value for a string 'true'.
The Plugin works as intended now. This was using WordPress 6.5.2 and CoCart 3.12.0.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `trunk` branch of CoCart on GitHub.
- [ ] The issue still exists against the latest `dev` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. Install WordPress v6.5.2 and CoCart 3.12.0
2. Make a fetch call with axios, set withCredentials: true to /wp-json/cocart/v2/cart

## Expected/actual behavior

Expected was an Access-Control-Allow-Credentials value of true, but acutally was 1.

## Isolating the problem

- [x] This bug happens with only WooCommerce and CoCart plugin are active.
- [x] This bug happens with a default WordPress theme active.
- [ ] This bug happens with the WordPress theme Storefront active.
- [ ] This bug happens with the latest release of WooCommerce active.
- [ ] This bug happens only when I authenticate as a customer.
- [ ] This bug happens only when I authenticate as administrator.
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
<html><body>

Version: |   | 3.12.0
-- | -- | --
Database Version: | <span class="woocommerce-help-tip" tabindex="0" aria-label="The  version of CoCart that the database is formatted for. This should be the  same as your CoCart version. Unless you have CoCart Pro, then it should  be the version of CoCart packaged." data-tip="The version of CoCart  that the database is formatted for. This should be the same as your  CoCart version. Unless you have CoCart Pro, then it should be the  version of CoCart packaged."></span> | 3.12.0
Install Date: |   | April 10, 2024
Carts in Session: |   | 10
Carts Active: |   | 10 out of 10 in session.
Carts Expiring Soon: | <span class="woocommerce-help-tip" tabindex="0"  aria-label="Carts that only have less than 6 hours left before they have  expired." data-tip="Carts that only have less than 6 hours left before  they have expired."></span> | 0 out of 10 in session.
Carts Expired: | <span class="woocommerce-help-tip" tabindex="0" aria-label="Any  expired carts that get updated before being cleared will become an  active cart again." data-tip="Any expired carts that get updated before  being cleared will become an active cart again."></span> | 0 out of 10 in session.
Carts Source (by CoCart): |   | 8
Carts Source (by Web): |   | 1
Carts Source (by Other): | <span class="woocommerce-help-tip" tabindex="0"  aria-label="These carts were created other than CoCart or WooCommerce."  data-tip="These carts were created other than CoCart or  WooCommerce."></span> | 1

</body>
</html>
</details>

**Comment by seb86** [comment]
Thanks for reporting the issue @SebastianLamprecht

**Comment by SebastianLamprecht** [comment]
Thank you for your quick follow up!
