### ISSUE TITLE
"Class "ReserveStock" not found" after Wodpress Automatic update 3.12.0 > 4.0.0

### ISSUE THREAD

**Issue by hund-ernesto** [co-cart/co-cart#414]
## Describe the bug

Tuesday 14/05 the plugin on one of my e-commerce websites updated from version 3.12.0 to version 4.0.0. Since the update, it has become impossible to add products to the cart, and the WordPress log started reporting a Fatal Error, which I'm attaching below:

```
Fatal error: Uncaught Error: Class "ReserveStock" not found in /home/*****/*****/wp-content/plugins/cart-rest-api-for-woocommerce/includes/api/cocart/v2/cart/class-cocart-cart-controller.php:2209
```

I rolled back to the previous version (3.12.0), and everything started working correctly again.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `trunk` branch of CoCart on GitHub.
- [ ] The issue still exists against the latest `dev` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. Let plugin auto-update on Wordpress
2. Cleaned all CACHE
3. Add a product to cart
4. Watch it fail
5. Check the LOG and find the Fatal error

## Expected/actual behavior

Product should be add to cart.

When I follow those steps, I see...

```
Fatal error: Uncaught Error: Class "ReserveStock" not found in /home/*****/*****/wp-content/plugins/cart-rest-api-for-woocommerce/includes/api/cocart/v2/cart/class-cocart-cart-controller.php:2209
```

## Isolating the problem

- [x] This bug happens with only WooCommerce and CoCart plugin are active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] This bug happens with the WordPress theme Storefront active.
- [ ] This bug happens with the latest release of WooCommerce active.
- [ ] This bug happens only when I authenticate as a customer.
- [ ] This bug happens only when I authenticate as administrator.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by seb86** [comment]
Sorry about that. Not sure how it passed our tests but it appears a line was unintentionally removed. Patch will be out shortly.

**Comment by seb86** [comment]
Issue resolved. v4.0.1 released.

**Comment by hund-ernesto** [comment]
Updated to 4.0.1 and everything run smoothly.
This is what speed looks like... thank you very much.
