### ISSUE TITLE
API document link invalid

### ISSUE THREAD

**Issue by LeonAppDev** [co-cart/co-cart#43]
Not a big issue, but think you should know the link to the document in your readme file does not work,  it looks not professional so if possible, please fix it. 
![image](https://user-images.githubusercontent.com/10129395/46775098-2f5e5300-cd62-11e8-886d-4bf5a7edead7.png)

**Comment by seb86** [comment]
I am aware of it @LeonAppDev. The repository was recently renamed and changes will be coming soon.
