### ISSUE TITLE
Idea: Support ClassicPress + Classic Commerce

### ISSUE THREAD

**Issue by seb86** [co-cart/co-cart#448]
I took a look at ClassicPress for an hour as I was curious how well it holds up. From the brief experiment, I would say that CoCart is mostly supported for just the core of what WooCommerce use to be below v3.6. There are a few functions that are unavailable that CoCart requires that where introduced in WooCommerce v3.6 but there is a possibility of a work around with some adjusting.

While I wouldn't normally look into going backwards, I do like the idea of using what was great about WooCommerce before the bloat it now has which has reduced some of it's performance. Yes, there is now a more optimized database for orders and products are indexed better, but it still has some flaws. Not everything can be perfect. I get that. But with the recent drama that has happened with WordPress (WP vs WP Engine or Matt vs WP Engine or Matt vs WP Community). It got me thinking of protecting CoCart and limited by one platform.

Plus, ClassicPress has removed any bloat to improve performance that has been added since Gutenberg. So using the REST API is going to have a significant performance improvement than what WordPress has today.

Since ClassicPress is technically WordPress, it's not much of a stretch to support it as well even if the forked version of WooCommerce is at a lower version than what CoCart currently supports. However, it's still a version that CoCart started out with.

If anyone has been interested in using ClassicPress. Let me know your thoughts about this.

> P.S. Please bare in mind that Classic Commerce has not had any further development since 2021 and may not support any WooCommerce extension that is currently available due to compatibility and connectivity. You would have to find a version from the time WooCommerce v3.5 was out.

**Comment by seb86** [comment]
Oh. According to their site Classic Commerce is not maintained. https://directory.classicpress.net/plugins/classic-commerce/

**Comment by seb86** [comment]
Forum for Classic Commerce: https://forums.classicpress.net/tag/classic-commerce

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by seb86** [comment]
> to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html) maybe this will solve your problem.

What is this?

**Comment by seb86** [comment]
Decided this would be too much work if Classic Press is not supporting it. Closing the issue.
