### ISSUE TITLE
ISBAT remove item from cart for authenticated users, but item still appears after removal

### ISSUE THREAD

**Issue by widdydev** [co-cart/co-cart#461]
## Describe the bug

After removing an item from the cart, it remains in the cart despite a success message confirming its removal. This issue occurs only for authenticated users. For guest users using the `cart_key` query parameter, the removal works as expected.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `trunk` branch of CoCart on GitHub.
- [x] The issue still exists against the latest `development` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue

1.	Authenticate a user via the `Authorization` header.
2.	Retrieve the cart using the [Get Cart](https://docs.cocart.xyz/?ref=devresources#cart-get-cart) endpoint and inspect the cart items.
3.	Remove an item by its `item_key` using the [Remove Item From Cart](https://docs.cocart.xyz/?ref=devresources#items-in-cart-remove-item-from-cart) endpoint. Confirm the success message in the notices property of the response.
4.	Retrieve the cart again via the [Get Cart](https://docs.cocart.xyz/?ref=devresources#cart-get-cart) endpoint. The previously removed item (identified by the same `item_key`) still appears in the cart.

## Expected/actual behavior

When following these steps, the item marked for removal still appears in the cart, despite a prior success message confirming its removal.

I expected the cart response to exclude the item with the specified `item_key`.

## Isolating the problem

- [x] This bug happens with only WooCommerce and CoCart plugin are active.
- [x] This bug happens with a default WordPress theme active.
- [x] This bug happens with the WordPress theme Storefront active.
- [x] This bug happens with the latest release of WooCommerce active.
- [x] This bug happens only when I authenticate as a customer.
- [ ] This bug happens only when I authenticate as administrator.
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.4.1
Legacy REST API Package Version: ✔ 1.0.4
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: ❌ 6.6.2 - Es ist eine neuere Version von WordPress verfügbar (6.7)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: nginx/1.25.5
PHP Version: 8.1.28
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 10.11.5-MariaDB-1:10.11.5+maria~ubu2004
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1388
avada_faq: 1
awsm_team: 1
awsm_team_member: 24
br_filters_group: 1
br_product_filter: 6
custom_css: 1
document_template: 4
em_booking: 24
em_event: 3
em_performer: 5
event: 3
fusion_element: 1
fusion_form: 2
fusion_tb_layout: 6
fusion_tb_section: 20
location: 1
mec-books: 16
mec-events: 6
nav_menu_item: 44
oembed_cache: 9
page: 44
popup: 1
popup_theme: 8
post: 4
postman_sent_mail: 10
product: 678
revision: 842
shipping_package: 2
shop_coupon: 4
shop_order: 33204
slide: 18
user_registration: 1
was: 6
wcsf: 1
wcsf_question: 7
wp_global_styles: 1
wpf_product_options: 1
wpforms: 5
yith-wcbm-badge: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (44) ###

Ajax Cart AutoUpdate for WooCommerce: von taisho – 1.5.5
FiboSearch - AJAX Search for WooCommerce (Pro): von FiboSearch Team – 1.29.0
AWSM Team Pro: von AWSM Innovations – 1.10.2
CoCart API - Decoupling Made Easy for WooCommerce: von CoCart Headless
LLC – 4.3.9

Conditional Logic for Woo Product Add-Ons Premium: von Meow Crew – 2.1.6
Contact Form 7: von Takayuki Miyoshi – 6.0
CS - Registerkarten / Registerfelder: von Christopher Slapal – 1.0.0
CS - Versandkosten: von Christopher Slapal – 1.0.0
CS - YoutubeVideosII: von Christopher Slapal – 1.0.0
CS - Lieferdatum: von Christopher Slapal – 1.0.0
CS - Mein Konto Design: von Christopher Slapal – 1.0.0
CS - Mindestbestellwert: von Christopher Slapal – 1.0.0
Disable XML-RPC Pingback: von Samuel Aguilera – 1.2.2
Export All URLs: von Atlas Gondal – 4.7.1
Avada Builder: von ThemeFusion – 3.11.11
Avada Core: von ThemeFusion – 5.11.11
JWT Auth - Extend Token Expiration: von Lukas Wittich – 1.0.0
JWT Auth: von Useful Team – 3.0.2
Kadence WooCommerce Email Designer: von Kadence WP – 1.5.13
Loco Translate: von Tim Whitlock – 2.6.11
Order Status Control for WooCommerce: von Bright Plugins – 1.0.3
Product Import Export for WooCommerce: von WebToffee – 2.4.8
Slider Revolution: von ThemePunch – 6.6.20
ShortPixel Image Optimizer: von ShortPixel - Convert WebP/AVIF & Optimize Images – 5.6.4
TI WooCommerce Wishlist: von TemplateInvaders – 2.9.1
vendidero Helper: von vendidero – 2.2.5
weLaunch-Framework: von weLaunch.io – 1.1.1
WPC Product Bundles for WooCommerce: von WPClever – 8.1.3
WooCommerce.com Update Manager: von Automattic – 1.0.3
WooCommerce Advanced Shipping - Advanced Pricing: von Jeroen Sormani – 2.2.1
WooCommerce Advanced Shipping Packages: von Jeroen Sormani – 1.2.1
WooCommerce Advanced Shipping: von Jeroen Sormani – 1.0.14
WooCommerce AJAX Products Filter: von BeRocket – 3.1.4.6
Checkout Field Editor for WooCommerce: von ThemeHigh – 3.1.5
WooCommerce Legacy REST API: von WooCommerce – 1.0.4
Advanced Order Export For WooCommerce (Pro): von AlgolPlus – 3.4.2
WooCommerce-Druckprodukte: von weLaunch – 1.8.12
WooCommerce Produkt-Add-ons: von Woo – 7.1.2
WooCommerce Step Filter: von troll_winner@mail.ru – 8.0.0
WooCommerce: von Automattic – 9.4.1
Yoast SEO: von Team Yoast – 23.8
WP Mail Logging: von WP Mail Logging Team – 1.13.1
WP Mail SMTP: von WP Mail SMTP – 4.2.0
WPForms Lite: von WPForms – 1.9.2.1

### Inactive Plugins (8) ###

CS - Geburtsdatum: von Christopher Slapal – 1.0.0
CS - Gutschein Fixieren: von Christopher Slapal – 1.0.0
CS - Gutschein Umbenennen: von Christopher Slapal – 1.0.0
CS - Spezial Buttons: von Christopher Slapal – 1.0.0
CS - YoutubeVideos: von Christopher Slapal – 1.0.0
CS – Rabattsammler: von Christopher Slapal – 1.0.0
Maintenance: von WebFactory Ltd – 4.15
XML Sitemap & Google News: von RavanH – 5.4.9

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

Kinsta Must-use Plugins: von Kinsta Team – 3.1.1

### Settings ###

Legacy API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 Tage
Level threshold: –
Log directory size: 90 kB

### WC Pages ###

Shop-Basis: #19725 - /shopneu/
Warenkorb: #16564 - /warenkorb/ -  Enthält den [woocommerce_cart]-Shortcode
Kasse: #16586 - /kasse/ -  Enthält den [woocommerce_checkout]-Shortcode
Mein Konto: #16576 - /mein-konto/
Allgemeine Geschäftsbedingungen: #19996 - /agb-speisenzusteller/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.11.11
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-14 11:52:36 +01:00
Options: ✔
Notes: 41
Onboarding: completed

### Templates von TI WooCommerce Wishlist ###

Überschreibt: –

### Action Scheduler ###

Abgeschlossen: 2.164
Oldest: 2024-10-14 12:59:28 +0200
Newest: 2024-11-14 11:44:57 +0100

Fehlgeschlagen: 461
Oldest: 2021-12-22 08:42:25 +0100
Newest: 2024-11-09 14:03:09 +0100

Ausstehend: 7
Oldest: 2024-11-14 12:34:50 +0100
Newest: 2024-11-18 01:00:00 +0100


### CoCart ###

Version: 4.3.9
Database Version: 4.3.9
Install Date: 02.02.2022
Cart Sessions: 
Carts in Session: 21643
Carts Active: 21402 out of 21643 in session.
Carts Expiring Soon: 214 out of 21643 in session.
Carts Expired: 241 out of 21643 in session.
Carts Created (by CoCart): 20535
Carts Created (by Web): 1108
Carts Created (by Other): 0

### Status report information ###

Generated at: 2024-11-14 11:47:50 +01:00
```
</details>
</details>

**Comment by seb86** [comment]
This is an issue with the authentication. Check that the token has not expired.

**Comment by widdydev** [comment]
> This is an issue with the authentication. Check that the token has not expired.
Thank you for the hint @seb86.

Unfortunately, this issue persists even with a newly generated token (valid for 10 minutes) when all steps are completed within a minute. I highly doubt that the token expires within such a short timeframe. Can you provide any other suggestions for resolving this issue?

**Comment by seb86** [comment]
It's a JWT issue for sure, as you will find that basic authentication works fine. I dont know why it's just this end point for you. I get random reports on these from time to time. It appears this particular JWT plugin has made a major change in v3. I [recommend the other JWT plugin](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/).

**Comment by widdydev** [comment]
> It's a JWT issue for sure, as you will find that basic authentication works fine. I dont know why it's just this end point for you. I get random reports on these from time to time. It appears this particular JWT plugin has made a major change in v3. I [recommend the other JWT plugin](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/).

I've just tested our integration with the recommended JWT plugin and I'm getting the same results.
Is there anything else I can try?

Thanks in advance!

**Comment by seb86** [comment]
Well if it's not your server not allowing delete requests then I recommend using [our JWT plugin](https://wordpress.org/plugins/cocart-jwt-authentication/) designed for CoCart. If then it's still not working I will look into the issue further.

**Comment by widdydev** [comment]
This did not solve the issue either. The response from the remove item endpoint refers to the correct customer (correct id, name etc.). Also the response cart data shows the expected state of the cart (Without the previously removed item). The success message says that the action was successful.
Bug again after calling get cart again, the removed item appears in the cart again.

**Comment by seb86** [comment]
Version 4.3.11 just released to help with cache related issues. Let me know if that helped your situation please.

**Comment by sufiyan05** [comment]
@seb86 we are using Version 4.3.13 and still we are facing this issue in production server our app is not functioning due to this issue.

**Comment by seb86** [comment]
I understand your concern and I appreciate your patience while I try to solve this problem.

**Comment by seb86** [comment]
I can confirm that the product does remove and return a successful response but it also remains in the cart at the same time so I don't think it's the endpoint specifically that is the issue and it's not related to just JWT authentication. It happens with basic authentication too. Still unsure why that is but my theory is that it's related to the mechanics of persistent cart for registered customers and is merging items after removing an item before saving the session so it appears as if the remove part is interrupted.

**Comment by seb86** [comment]
However, if I try to remove the item again it then wipes out the cart of any remaining items. 😮‍💨

**Comment by seb86** [comment]
Can confirm API v1 does the same, I even disabled cart price cache, cart validation and formatting so it's something deeper. Still looking.

**Comment by seb86** [comment]
May have found the culprit of the issue. If you all can confirm for me on your end by editing the `class-cocart-authentication.php` file and disable this filter `add_filter( 'rest_authentication_errors', array( $this, 'cocart_user_logged_in' ), 10 );` and try deleting an item again.

Source: https://github.com/co-cart/co-cart/blob/trunk/includes/classes/rest-api/class-cocart-authentication.php#L110

**Comment by widdydev** [comment]
> May have found the culprit of the issue. If you all can confirm for me on your end by editing the `class-cocart-authentication.php` file and disable this filter `add_filter( 'rest_authentication_errors', array( $this, 'cocart_user_logged_in' ), 10 );` and try deleting an item again.
> 
> Source: https://github.com/co-cart/co-cart/blob/trunk/includes/classes/rest-api/class-cocart-authentication.php#L110

Yes this solves the issue on my side!
Thank you for your support and commitment!

**Comment by seb86** [comment]
Great. Now I got to figure out why it affects deleting ONLY!

**Comment by seb86** [comment]
More accurately it's because of [this one line](https://github.com/co-cart/co-cart/blob/trunk/includes/classes/rest-api/class-cocart-authentication.php#L150), the rest of the filter is fine.

**Comment by seb86** [comment]
Solved by adding a condition to not trigger it when a DELETE request method is called. Patch will be out soon.

**Comment by seb86** [comment]
Patch v4.3.14 now released @widdydev @sufiyan05

**Comment by widdydev** [comment]
I've updated the plugin to 4.3.14. But it still does not work on my side. @sufiyan05 was it fixed for you?

**Comment by seb86** [comment]
What? Item removed with no issues for me after that change.

**Comment by sufiyan05** [comment]
> I've updated the plugin to 4.3.14. But it still does not work on my side. @sufiyan05 was it fixed for you?

Yes i have updated the plugin to 4.3.14, But it still does not work on my side also @widdydev 

@seb86  i have used woocommerce Version 9.0.3 still getting issues.

**Comment by seb86** [comment]
Well, I'm stumped. Results show it working for me again. Mind experimenting on your end editing the area that causes the problem? See previous comments.

**Comment by sufiyan05** [comment]
> Well, I'm stumped. Results show it working for me again. Mind experimenting on your end editing the area that causes the problem? See previous comments.

as you suggest the above solution it's working but still getting removed items after logout and login again.

**Comment by seb86** [comment]
OK I'm still reviewing. Will open a new issue once I have definitive details as to what happened.
