### ISSUE TITLE
ISBAT Fetch a single product

### ISSUE THREAD

**Issue by leonelectro** [co-cart/co-cart#462]
/wp-json/cocart/v2/products/123 returns a PHP fatal due to argument count being 1 instead of 2. Tested in version 4.3.9. Using PHP 8.3.

    Too few arguments to function CoCart_Security::remove_exposed_product_meta(), 1 passed in /code/wp-includes/class-wp-hook.php on line 326 and exactly 2 expected
    
    #0 /code/wp-includes/class-wp-hook.php(326): CoCart_Security-&gt;remove_exposed_product_meta(Array)<br />
    #1 /code/wp-includes/plugin.php(205): WP_Hook-&gt;apply_filters(Array, Array)<br />
    #2 /code/wp-content/plugins/cart-rest-api-for-woocommerce/includes/classes/rest-api/controllers/v2/products/class-cocart-products-controller.php(1084): apply_filters(&#039;cocart_products...&#039;, Array, Object(WC_Product_Simple))<br />
    #3 /code/wp-content/plugins/cart-rest-api-for-woocommerce/includes/classes/rest-api/controllers/v2/products/class-cocart-products-controller.php(575): CoCart_REST_Products_V2_Controller-&gt;get_meta_data(Object(WC_Product_Simple))<br />
    #4 /code/wp-content/plugins/cart-rest-api-for-woocommerce/includes/classes/rest-api/controllers/v2/products/class-cocart-products-controller.php(197): CoCart_REST_Products_V2_Controller-&gt;get_product_data(Object(WC_Product_Simple))<br />
    #5 /code/wp-content/plugins/cart-rest-api-for-woocommerce/includes/classes/rest-api/controllers/v2/products/class-cocart-products-controller.php(365): CoCart_REST_Products_V2_Controller-&gt;prepare_object_for_response(Object(WC_Product_Simple), Object(WP_REST_Request))<br />
    #6 /code/wp-includes/rest-api/class-wp-rest-server.php(1230): CoCart_REST_Products_V2_Controller-&gt;get_item(Object(WP_REST_Request))<br />
    #7 /code/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server-&gt;respond_to_request(Object(WP_REST_Request), &#039;/cocart/v2/prod...&#039;, Array, NULL)<br />
    #8 /code/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server-&gt;dispatch(Object(WP_REST_Request))<br />
    #9 /code/wp-includes/rest-api.php(420): WP_REST_Server-&gt;serve_request(&#039;/cocart/v2/prod...&#039;)<br />
    #10 /code/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))<br />
    #11 /code/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)<br />
    #12 /code/wp-includes/plugin.php(565): WP_Hook-&gt;do_action(Array)<br />
    #13 /code/wp-includes/class-wp.php(418): do_action_ref_array(&#039;parse_request&#039;, Array)<br />
    #14 /code/wp-includes/class-wp.php(813): WP-&gt;parse_request(&#039;&#039;)<br />
    #15 /code/wp-includes/functions.php(1336): WP-&gt;main(&#039;&#039;)<br />
    #16 /code/wp-blog-header.php(16): wp()<br />
    #17 /code/index.php(17): require(&#039;/code/wp-blog-h...&#039;)<br />
    #18 {main}

**Comment by seb86** [comment]
@leonelectro Thanks for letting me know. Hot fix releasing shortly.
