### ISSUE TITLE
Removing cart item (DELETE) returns said cart item in the next cart call

### ISSUE THREAD

**Issue by jnz31** [co-cart/co-cart#474]
## Describe the bug

i call DELETE on a product in my cart via `/v2/cart/item/${item_key}`.
that deletes the item and puts it into `removed_items` array. but with the next POST call, lets say for updating stock on another item in the cart, or deleting further items in the cart, i get the previously deleted item back in cart (and in removed_items)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate. (not sure if its related to https://github.com/co-cart/co-cart/issues/471)
- [x] The issue still exists against the latest `trunk` branch of CoCart on GitHub.
- [x] The issue still exists against the latest `development` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue

1. add items to cart
2. delete item in cart
3. adjust cart (add, delete, update) => wrong cart contents

## Expected/actual behavior

items get deleted on delete call and cart looks proper until you load/adjust the cart again.

## Isolating the problem

- [x] This bug happens with only WooCommerce and CoCart plugin are active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] This bug happens with the WordPress theme Storefront active.
- [x] This bug happens with the latest release of WooCommerce active.
- [ ] This bug happens only when I authenticate as a customer.
- [ ] This bug happens only when I authenticate as administrator.
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
```
<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.4.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 16 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.25
PHP Post Max Size: 75 MB
PHP Time Limit: 15
PHP Max Input Vars: 1500
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.6.19-MariaDB
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
acf-ui-options-page: 1
attachment: 4107
customize_changeset: 2
nav_menu_item: 23
oembed_cache: 1
page: 19
pos_grid: 1
pos_outlet: 2
pos_receipt: 1
pos_register: 2
pos_session: 19
post: 3
product: 1015
product_variation: 2326
revision: 259
shop_coupon: 13
shop_order_placehold: 385
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 2
wp_navigation: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Advanced Access Manager: by AAM  – 6.9.43
Advanced Custom Fields PRO: by WP Engine – 6.3.11
All In One WP Security: by TeamUpdraft
DavidAnderson – 5.3.4

CoCart API - Decoupling Made Easy for WooCommerce: by CoCart Headless
LLC – 4.3.14

CoCart Plus: by CoCart Headless
LLC – 1.5.4

CSV-Export: by Andreas Buss – 1.0.0
Disable Emojis (GDPR friendly): by Ryan Hellyer – 1.7.6
Facebook for WooCommerce: by Facebook – 3.3.0
Index WP MySQL For Speed: by Oliver Jones
Rick James – 1.5.2

Password Protected: by Password Protected – 2.7.5
Post SMTP: by Post SMTP – 2.9.11
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Relevanssi: by Mikko Saari – 4.23.1
REST API Data Localizer: by Brandon Shiluk – 1.0.0
Show Current Template: by JOTAKI Taisuke – 0.5.2
TikTok: by TikTok – 1.2.10
UpdraftPlus - Backup/Restore: by TeamUpdraft
DavidAnderson – 1.24.11

WooCommerce UPS Shipping Plugin with Print Label: by PluginHive – 6.1.8
W3 Total Cache: by BoldGrid – 2.8.0
WooCommerce.com Update Manager: by Automattic – 1.0.3
Gift Wrapper: by Gift Wrapper – 6.2.2
WooCommerce PayPal Payments: by WooCommerce – 2.9.4
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.9.0
PDF Invoices & Packing Slips for WooCommerce - Professional: by WP Overnight – 2.15.11
PDF Invoices & Packing Slips for WooCommerce - Premium Templates: by WP Overnight – 2.19.6
Point of Sale for WooCommerce: by Actuality Extensions – 6.3.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.3.2
Diez-API: by Jens Buss – 1.0.0
WooCommerce: by Automattic – 9.4.2
Yoast SEO: by Team Yoast – 23.9
WP All Import Pro: by Soflyy – 4.8.7
WP REST Cache: by Acato – 2024.2.3
Perfect Images (Optimize, Rebuild, Replace, Thumbnails, Retina): by Jordy Meow – 6.6.6
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 4.0.0
WP Overnight Sidekick: by WP Overnight – 2.5.1

### Inactive Plugins (3) ###

Simple Custom Post Order: by Colorlib – 2.5.8
WooCommerce Shipping & Tax: by WooCommerce – 2.8.3
WP-Optimize - Clean, Compress, Cache: by TeamUpdraft
DavidAnderson – 3.7.1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db.php: db.php
object-cache.php: object-cache.php

### Must Use Plugins (3) ###

Index WP MySQL For Speed Upgrade Filter for mu-plugins.: by  – 1.5.2
simba-tfa-encryption-key.php: by  –
WP REST Cache - Must-Use Plugin: by Richard Korthuis - Acato – 2021.3.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 25 MB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/ -  Contains the woocommerce/cart block
Checkout: #9 - /checkout/ -  Contains the woocommerce/checkout block
My account: #10 - /account/
Terms and conditions: #7293 - /info/terms-of-use/

### Theme ###

Name: blank
Version: 1.0.1
Author URL: https://github.com/bucky355
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: blank/single-product.php version - is out of date. The core version is 1.6.4
Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled
PayPal Shipping Callback: ✔
Apple Pay: –
Google Pay: –
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-27 10:07:20 +00:00
Options: ✔
Notes: 79
Onboarding: completed

### Action Scheduler ###

Complete: 12,979
Oldest: 2024-10-26 15:34:39 +0000
Newest: 2024-11-26 14:19:21 +0000

Failed: 50
Oldest: 2024-06-13 10:30:21 +0000
Newest: 2024-11-20 16:17:55 +0000

Pending: 5
Oldest: 2024-11-26 20:15:26 +0000
Newest: 2024-12-06 16:15:00 +0000

### CoCart ###

Version: 4.3.14
Database Version: 4.3.14
Install Date: June 13
2024

Cart Sessions: 
Carts in Session: 23154
Carts Active: 19846 out of 23154 in session.
Carts Expiring Soon: 1954 out of 23154 in session.
Carts Expired: 3308 out of 23154 in session.
Carts Created (by CoCart): 276
Carts Created (by Web): 22878
Carts Created (by Other): 0

### Status report information ###

Generated at: 2024-11-26 14:23:21 +00:00
```
</details>
```
</details>

**Comment by jnz31** [comment]
<img width="1121" alt="Bildschirmfoto 2024-11-26 um 14 48 13" src="https://github.com/user-attachments/assets/c3e8cb77-a55e-4faa-8883-ea5fe57be49d">

**Comment by seb86** [comment]
Why it only affects the deleting of an item is still unclear but I know it's related to changes made from v4.2 The last patch was only a small fix. Unfortunately, it's not the whole thing until the root of the issue if resolved. What's also strange is that the response is not 100% match against the schema.

**Comment by seb86** [comment]
Testing looks good.

**Comment by seb86** [comment]
@jnz31 @widdydev @sufiyan05 Please test the build below and let me know if everything is working now for you.

[cart-rest-api-for-woocommerce-v4.3.15.zip](https://github.com/user-attachments/files/17950899/cart-rest-api-for-woocommerce-v4.3.15.zip)

**Comment by jnz31** [comment]
cheers! just installed this on my staging with the error at hand. after uploading and adjusting the cart, the problem was not reoccurring 👍
