### ISSUE TITLE
Add Coupon coupon endpoint 

### ISSUE THREAD

**Issue by mezzat11** [co-cart/co-cart#48]
Hello 
I noticed the closing issue of the coupons. Have you added it?
Thank you .

**Comment by seb86** [comment]
It will be added to CoCart Pro. 😃

**Comment by mezzat11** [comment]
When will the other version be released?

**Comment by seb86** [comment]
Hopefully before XMAS. Currently improving one particular core feature before adding anything new. Will announce more on the site soon.

**Comment by joshuaiz** [comment]
+1 for this. Just tried to work with a coupon and I can add and list one but no way to apply it to the cart. Thanks Seb!!!
