### ISSUE TITLE
Cart items should not be shared by users

### ISSUE THREAD

**Issue by ruucm-working** [co-cart/co-cart#50]
## Expected/actual behaviour

Cart items should not be shared by users

but it is sharing all cart items 

I've tested on VVV, and real server (below LINK, anyone can test it using 'ADD TO CART button')
[Link](https://cnyttan.com/product/urban-stripe/)

What can I do?

**Comment by seb86** [comment]
What do you mean by shared? What are you doing? Need more information.

**Comment by ruucm-working** [comment]
@seb86

**Comment by ruucm-working** [comment]
@seb86 

When I add cart item using this API, it also shows up on the other my laptop & desktop

and it even doesn't care user logged in or not

**Comment by seb86** [comment]
That should not be happening because the cart is controlled by session. What language are you using the API in?

**Comment by ruucm-working** [comment]
it's javascript(react)

**Comment by ruucm-working** [comment]
Sure. This is code that I use with [wc-api-node](https://github.com/woocommerce/wc-api-node#readme)

```
 wc.get('cart', function(err, data, res) {
        let result = JSON.parse(res)
        dispatch(getDatas('cart', result, props.sort, props.category)) // dispatch value with key 'cart' (redux)
})
```

After some search, I realize this **weird sharing** happens every time when client side code access to server rest parts.

It also happens even I tested with pure wordpress add cart button..

**Comment by seb86** [comment]
Looks like it. So you have managed to build using WooCommerce's official NODE wrapper. That's cool. I thought they all require authentication which CoCart does not.
