### ISSUE TITLE
Feature: Check stock of cart items

### ISSUE THREAD

**Issue by botoxparty** [co-cart/co-cart#51]
Hey,

In my implementation I have added an endpoint to check the stock of all the cart items to make sure they are still in stock before proceeding to the checkout.

Feel free to implement, this is a very basic version. Could write something that returned a bit more than just an error with a string in it.

```
// Check Cart Stock - wc/v2/cart/check_stock (GET)
register_rest_route( $this->namespace, '/' . $this->rest_base  . '/check_stock', array(
	'methods'  => WP_REST_Server::READABLE,
	'callback' => array( $this, 'check_stock' ),
));
```

```
/**
 * Returns whether the cart items are in stock.
 *
 * @access public
 * @since  1.0.6
 * @return array
 */
public function check_stock() {
	$check = WC()->cart->check_cart_item_stock();

	return $check;
} // END check_stock()()
```

**Comment by seb86** [comment]
Hi @botoxparty 

That would be a cool feature to add. What would you want returned besides the error message that is returned?

**Comment by botoxparty** [comment]
I would return an array of which items are out of stock. Maybe this is already whats happening but i've only been testing with 1 out of stock product.

Actually I have moved the stock checking to the cart item object like this:

`$cart[$item_key]['in_stock'] = $_product->is_in_stock();`
`$cart[$item_key]['on_backorder'] = $_product->is_on_backorder();`

This allows me to save the extra API call to check the stock levels, and then i can display a message with each cart item saying it's either out of stock, or there will be a delay for that particular item because it's on backorder.

**Comment by seb86** [comment]
> I would return an array of which items are out of stock. Maybe this is already whats happening but i've only been testing with 1 out of stock product.

I think it already does.

> Actually I have moved the stock checking to the cart item object like this:

```
$cart[$item_key]['in_stock'] = $_product->is_in_stock();
$cart[$item_key]['on_backorder'] = $_product->is_on_backorder();
```

This could be a great first push if you are interested in submitting a pull request. Don't forget to create a new issue explaining what it does and how it can be of use when calling the cart.

You may need to add a condition should that product or the store not manage stock to prevent issues with the API returned.

**Comment by botoxparty** [comment]
Okay cool,

I'll put something together this weekend, there's a few other modifications i've made such as supporting product variations in the returned cart. The way its currently working is that it returns the parent product rather than the actual variation.

I also return the `count` with the get_cart method, saves another API call.

**Comment by metemaddar** [comment]
Hello, Thanks again for great plugin.
I think this is also needed in update or post too.

When we check the "Manage Stock Amount" on product. and we run out of product while adding, The API faces error 500.
Unfortunately I couldn't detect the cause. <a href="https://stackoverflow.com/questions/7149030/php-return-500-error-but-no-error-log">Maybe because of the way using some functions so that php did not log the error</a>.

**So how to regenerate the situation:**
We should make a product with "managed stock amount" in product admin.
For example we set the stock amount to 2;
and when we add the first two products, it is ok. But when we request another one to add to basket, The API returns error 500
