### ISSUE TITLE
Bug: Not compatible with WooCommerce 3.6

### ISSUE THREAD

**Issue by gelaxe** [co-cart/co-cart#55]
Explanation of problem found  here: https://barn2.co.uk/managing-cart-rest-api-woocommerce-3-6/ This helps me.

**Comment by seb86** [comment]
CoCart was mention in [this pull](https://github.com/woocommerce/woocommerce/pull/21090) but I was not so I did not get notified of this break.

**Comment by seb86** [comment]
Fix requires testing. [Here is the first RC](https://github.com/co-cart/co-cart/releases/tag/v1.1.0-rc.1) for CoCart

**Comment by gelaxe** [comment]
> Fix requires testing. [Here is the first RC](https://github.com/co-cart/co-cart/releases/tag/v1.1.0-rc.1) for CoCart

Now working.

**Comment by seb86** [comment]
@gelaxe Thank you for reporting this issue.

**Comment by princeandrew01** [comment]
I can confirm the release candidate is working for me and I am using it for a mobile app I am working on currently.

**Comment by andykeith** [comment]
Hi Sebastian, glad my post was helpful (barn2.co.uk). I was going to give you a heads up as I saw you might be affected by this, but we’ve been busy getting our plugins tested with 3.6!! Let me know if you spot any problems with the workaround

**Comment by seb86** [comment]
@andykeith Thank you.
