### ISSUE TITLE
Notice: Use of undefined constant WC_VERSION - assumed 'WC_VERSION' was showed in my screen

### ISSUE THREAD

**Issue by hudsoncliff** [co-cart/co-cart#59]
Hi, I was using your plugin in my local environment and this notification came up in debugging mode.

the erro comes from this line.
/includes/class-wc-cart-rest-api-init.php on line 65

**Comment by merijnponzo** [comment]
Having the same problem since the latest update 1.2.0 of co-cart and woocommerce 3.6.3
now when I add a cart item i got a message 'problem with the security, please login again'
thanks. great plugin

**Comment by merijnponzo** [comment]
Where can I download the previous version? My webshop has to go live tomorrow :-(

**Comment by hudsoncliff** [comment]
@merijnponzo 

I think you can get a previous version by using a rollback plugin if you don't have you old version files backed up.

**Comment by seb86** [comment]
Thank you for reporting the issue @hudsoncliff  Taking a look at it now. Can you tell me if this is only if you have debug mode enabled?

**Comment by seb86** [comment]
Done. Releasing now!

**Comment by merijnponzo** [comment]
awesome, it works, thank you

**Comment by hudsoncliff** [comment]
Thanks!
its working good!
