### ISSUE TITLE
CoCart doesnt update item on cart when I reload cart

### ISSUE THREAD

**Issue by lucabarbosa** [co-cart/co-cart#71]
Hello folks,

I've been used CoCart in my SPA Woocommerce and it has been amazing!
However, I found a bug in the update_item endpoint.

When I update a product quantity, it works and returns the new cart with the correct quantity. However, when I call get-cart endpoint after update_item, the cart is the same as before updating the product quantity. 

It seems that cart data wasn't persisted.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of CoCart on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue
1. Add item to cart with '/wp-json/cocart/v1/add-item'
2. Update item in Cart with '/wp-json/cocart/v1/item'. (At this point, if I use 'return_cart' argument as true, the cart content returns correctly, but it doesn't on folllowing steps.)
3. Get cart contents with ' /wp-json/cocart/v1/get-cart'

## Expected/actual behaviour

When I follow those steps, I see the cart contents as if I'm not doing the second step. That is, the cart contents is not being updating.

I was expecting to see the cart contents updated.

## Isolating the problem

- [x] This bug happens with only WooCommerce and CoCart plugin are active.
- [x] This bug happens with a default WordPress theme active.
- [x] This bug happens with the WordPress theme Storefront active.
- [x] This bug happens with the latest release of WooCommerce active.
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment

Wordpress - 5.1.1
Woocommerce - 6.3.5
PHP - 7.3.1

**Comment by lucabarbosa** [comment]
UPDATE:

I did some tests and notice it:

When I use 'refresh_totals' argument in Update Item Endpoint, the cart content is updated correctly. When I don't use this argument, the cart content isn't updated correctly.

**Comment by 29satnam** [comment]
I had to add these headers to `/wp-json/cocart/v1/get-cart`:
`["User-Agent": "CoCart API/v1", "Accept": "application/json", "Content-Type": "application/json"]`
