### ISSUE TITLE
Feedback: Support for cart storing in session

### ISSUE THREAD

**Issue by seb86** [co-cart/co-cart#73]
Some of you have had issues with CoCart when developing with **Android** so my attempt to provide support in that area is in need of your feedback. Below is a changelog on what I have developed for the next release which I hope will provide the missing link and support for future features to come.

I have explained how it works and how to use this newly added support in [this blog post](https://cocart.xyz/cocart-v2-1-0-beta-2/). If you have any questions, I will be happy to answer them here.

I look forward to your feedback.

Thank you.

regards,

Sébastien.

## v2.1.0

* NEW: Added a new endpoint for fetching products or a singular product in READ-ONLY. No authentication required.
* NEW: Added support for guest carts.
* NEW: Cart data are stored in a new database table.
* NEW: Added plugin details to WooCommerce System Status.
* NEW: Added uninstall.php file to delete tables and options.
* Dev: Clear all carts stored in session via the Tools section of WC System Status.
* Dev: Cart expiration can be filtered if the default 48 hours is not to your liking.
* Dev: Cart key can be filtered before storing cart in the database and creates a cookie on the customer's device.
* Dev: Added conditional filter for returning a cart item.

> Note: Carts that have expired past 48 hours are cleared via a cron-job twice daily.
> This release is a work in progress and requires developer feedback.

[Download release](https://github.com/co-cart/co-cart/archive/v2.1.0-beta.4.zip).

**Comment by seb86** [comment]
New post about the new beta release. https://cocart.xyz/cocart-v2-1-0-beta-2/

**Comment by seb86** [comment]
So far no feedback which could be good news but would like a confirmation from someone if the changes in this release are on the right track. I know people are on holiday so I will leave this issue open a bit longer.

**Comment by seb86** [comment]
Anyone got any feedback, any questions?

**Comment by yagnikv** [comment]
when i call add to cart api with user login it was display website in  user cart empty and add product to admin cart in,so how can i solve it

**Comment by seb86** [comment]
@yagnikv Is this related to this?

**Comment by yagnikv** [comment]
@seb86 yes , but now i have solved it

**Comment by seb86** [comment]
Great. So what was the problem?

**Comment by yagnikv** [comment]
@seb86  is it possible? get cart responce is generate in array

**Comment by seb86** [comment]
Please refrain yourself for using issues for support. This is not related to the issue. Either create a ticket on the WordPress support forum or join the community on Slack. Thank you.

**Comment by seb86** [comment]
# v2.1.0-beta.4

## Changelog for this release

* Added: Counter for carts in session in WC system status.
* Corrected: Incorrect bool value used for initial item added to cart.
* Corrected: Value typo with cart key when storing cart to the database.
* Corrected: Version returned in WC system status for CoCart.
* Removed: Tax status and tax class for products data returned.
* Tweak: Fixed `create_tables()` should not be called statically 
* Tweak: Fixed `get_cart()` not called statically.

**Comment by Zacad** [comment]
Hello, i have strange behavior (both in 2.06 and 2.1).
When user (both guest and logged in user) just enter the site with no session the cart is empty. When user add some item to cart he is seeing his item, but also items added by other users, as if there is only one cart for each user instead of separate ones.

**Comment by seb86** [comment]
The issue is only in versions lower than 2.1 If you read the blog post you would have seen how to get the cart for a specific customer.

I'm actually close to a new beta release which I hope will improve this issue further.

Look out for details posted via the blog soon. Thank you.

**Comment by shendriksza** [comment]
I read the blog post but I'm still having a hard time understanding what you mean by storing cart in session. Is that not how CoCart already works?

**Comment by seb86** [comment]
@shendriksza It depends on the language you are using the API. Android for example does not handle sessions. This is what this version is designed to help improve on.

**Comment by danphilibin** [comment]
I'm having the same issue with guest carts with version 2.1. If I add a product to a brand new cart for Guest User 1, it returns a cart with a fresh `cocart_cart_key` but the new cart also contains the items from Guest User 2's cart, which has a different ID. And then Guest User 2's cart is updated with the item that Guest User 1 added. The keys are different but the contents are identical. The same thing happens when removing items, too – the item is removed from both carts.

So are you saying @seb86 that if the framework I'm using for API requests (in this case, React Native) doesn't handle sessions in a particular way, there's no way to have one guest cart per device until the next beta is released?

**Comment by shendriksza** [comment]
@seb86 Thanks that makes sense. But will this be breaking change of sessions used on the WordPress side, or is the idea to expose sessions data on the API so apps can store it themselves?

**Comment by seb86** [comment]
A new session handler has been developed and is working well with the recent commits I have made. I look forward to your feedback once the next beta is released.

@yagnikv @Zacad @shendriksza @danphilibin
