### ISSUE TITLE
Quantity should be passed through cocart_ok_to_add_(response)-filter

### ISSUE THREAD

**Issue by johan-vntrs** [co-cart/co-cart#76]
Hello!

For my use case, I'd like the requested quantity to be passed through the `cocart_ok_to_add` and `cocart_ok_to_add_filters`, since we have a special way of determining in-stock status. 

If needed, I can of course contribute with this addition. 

Thanks!

**Comment by seb86** [comment]
@johan-vntrs Please do.

**Comment by seb86** [comment]
@johan-vntrs Do you have a PR?

**Comment by seb86** [comment]
@johan-vntrs Added in commit f370542972d6475719acf083f8c69549d51e378c
