### ISSUE TITLE
New Endpoint: Get Products

### ISSUE THREAD

**Issue by seb86** [co-cart/co-cart#77]
Working on a read-only version of the products endpoint. If there is anything specific that you think is missing from the WooCommerce products endpoint that could be useful in CoCart's product endpoint. Leave a comment below.

**Comment by RichardLindhout** [comment]
Is there also coming a category endpoint?

**Comment by seb86** [comment]
@RichardLindhout Yes. I will be forking all products endpoint to be converted to a read-only version.

**Comment by RichardLindhout** [comment]
Nice, maybe keep in mind all the different variations a single product can have, I think there is no functionality available right know. Maybe a parameter to the url with selected variations and pushing back available options in the response.

**Comment by seb86** [comment]
Oh that would be great to add if it's missing. Send me some ideas.

**Comment by seb86** [comment]
I just skimmed through the REST API documentation for WC and saw nothing to filter the variation results and yet it's something that should be easy for them to include. Maybe it's coming in version 4.

**Comment by RichardLindhout** [comment]
Yep they do, although I don't think it's a bad idea to filter the variations in the front-end but it could be too much data on some products.

**Comment by seb86** [comment]
So a customer visits the product variation and selects the main attribute which is the colour. That then filters the variations by that attribute. As the customer selects more attributes (Gender, Size) it filters down some more. Is that what is required? I know on Amazon a variable product can show all variations but disables the other variations if it's not available for the main attribute. So for the REST API it would only return variations that are available based on the filtered attributes. Is that right?

**Comment by RichardLindhout** [comment]
Yes, I thinks that's the right approach.

Maybe look at this plugin, I think it already has some variations functions available: https://wordpress.org/plugins/woo-graphql-api/

**Comment by RichardLindhout** [comment]
https://plugins.trac.wordpress.org/browser/woo-graphql-api/trunk/includes/Helpers/Product.php#L67

**Comment by seb86** [comment]
Thank you for sharing that.

**Comment by RichardLindhout** [comment]
Is this plugin usable as mobile backend, it seems to me that the way the user is authenticated it can do everything in the woocommerce api. I want the user to only sync his own cart and nothing else.

**Comment by seb86** [comment]
If the user is logged in then yes it will sync to only their cart. Last update enabled the ability to use WooCommerce Authentication method again as it was restricted in WC latest releases.

**Comment by seb86** [comment]
I have [another issue](https://github.com/co-cart/co-cart/issues/73) that I am working on for guest customers. Currently in beta.

**Comment by RichardLindhout** [comment]
Thanks, will probably gonna test in the future if the project I'm estimating continues!

**Comment by erback** [comment]
Is this feature available in the beta version? Cannot see that the public product endpoint exists in the documentation.

**Comment by seb86** [comment]
Yes the products endpoint is available in the beta. [View the Work in Progress](https://docs.cocart.xyz/wip.html#products) section of the documentation.

**Comment by erback** [comment]
Thanks, should have looked closer!

**Comment by seb86** [comment]
@erback No problem.

**Comment by seb86** [comment]
Will now be an individual add-on.
