### ISSUE TITLE
How can I add a Yith composite product?

### ISSUE THREAD

**Issue by heshaShawky** [co-cart/co-cart#85]
I'm using the cocart for developing a mobile app and it's great, but when I send a request for adding product that it's a type of  'yith-composite' not adding the item components probably. or there's no on docs a way to add such a thing. 

I tried to do it from the wordpress site and it's working and when retrieved the response with post man to see what the response will look like I got the folloing: 

```json
{
    "2f4b582ce893dd25542e03196bef3e4d": {
        "yith_wcp_component_data": {
            "product_base_price": 0,
            "selection_data": {
                "AC8A73E7-072F-34B3-F67D-84973C7152BD": "100391",
                "6E456D90-AD39-7C26-C415-57CB081DB2D8": "100286"
            },
            "selection_variation_data": {
                "AC8A73E7-072F-34B3-F67D-84973C7152BD": "124196",
                "6E456D90-AD39-7C26-C415-57CB081DB2D8": ""
            },
            "selection_quantity": {
                "AC8A73E7-072F-34B3-F67D-84973C7152BD": "2",
                "6E456D90-AD39-7C26-C415-57CB081DB2D8": "1"
            },
            "cart_item_key": "2f4b582ce893dd25542e03196bef3e4d"
        },
        "key": "2f4b582ce893dd25542e03196bef3e4d",
        "product_id": 100387,
        "variation_id": 0,
        "variation": [],
        "quantity": 1,
        "data_hash": "535a95da7c81075e36e138daef9dc05e",
        "line_tax_data": {
            "subtotal": [],
            "total": []
        },
        "line_subtotal": 0,
        "line_subtotal_tax": 0,
        "line_total": 0,
        "line_tax": 0,
        "data": {},
        "product_name": "Emerald Green",
        "product_title": "Emerald Green",
        "product_price": "KD0.000"
    },
    "abbc2cd8274ac9bded191752ed8c61e9": {
        "yith_wcp_child_component_data": {
            "yith_wcp_component_parent_object": {},
            "yith_wcp_component_key": "AC8A73E7-072F-34B3-F67D-84973C7152BD",
            "yith_wcp_cart_parent_key": "2f4b582ce893dd25542e03196bef3e4d"
        },
        "key": "abbc2cd8274ac9bded191752ed8c61e9",
        "product_id": 100391,
        "variation_id": 124196,
        "variation": {
            "attribute_pa_sphere": "8-00"
        },
        "quantity": 2,
        "data_hash": "7c336acdb57e27f13058fc7592620f57",
        "line_tax_data": {
            "subtotal": [],
            "total": []
        },
        "line_subtotal": 15,
        "line_subtotal_tax": 0,
        "line_total": 15,
        "line_tax": 0,
        "data": {
            "ywcp_composite_info": {
                "composite_product_id": 100387,
                "composite_item_key": "AC8A73E7-072F-34B3-F67D-84973C7152BD"
            },
            "ywcp_bundled_price": "7.50",
            "virtual": "yes"
        },
        "product_name": "Emerald Green(right) &#8211; -8.00",
        "product_title": "Emerald Green(right)",
        "product_price": "KD7.500"
    },
    "661b13b1498c96d986728d137c092a2b": {
        "yith_wcp_child_component_data": {
            "yith_wcp_component_parent_object": {},
            "yith_wcp_component_key": "6E456D90-AD39-7C26-C415-57CB081DB2D8",
            "yith_wcp_cart_parent_key": "2f4b582ce893dd25542e03196bef3e4d"
        },
        "key": "661b13b1498c96d986728d137c092a2b",
        "product_id": 100286,
        "variation_id": 100286,
        "variation": [],
        "quantity": 1,
        "data_hash": "36f76fb62ac326633be66211f53a026c",
        "line_tax_data": {
            "subtotal": [],
            "total": []
        },
        "line_subtotal": 6.5,
        "line_subtotal_tax": 0,
        "line_total": 6.5,
        "line_tax": 0,
        "data": {
            "ywcp_composite_info": {
                "composite_product_id": 100387,
                "composite_item_key": "6E456D90-AD39-7C26-C415-57CB081DB2D8"
            },
            "ywcp_bundled_price": "6.50",
            "virtual": "yes"
        },
        "product_name": "Emerald Green(Left)",
        "product_title": "Emerald Green(Left)",
        "product_price": "KD6.500"
    }
}
```

**Comment by seb86** [comment]
Hi @heshaShawky 

Can you provide me the exact steps you are taking to add the product please?

**Comment by heshaShawky** [comment]
My client has a woocommerce site that uses custom product type called `yith-composite` that do the following:

1. a parent product 
2. a components product ( type: variable )

so it's actually more than one product: you can check that from the following link: 
https://kefan-optics.com/shop/1-day-freshlook-mystic-blue/

On the above link, you will find left-eye and right-eye, those are actually separated products.
links for them: 
https://kefan-optics.com/shop/1-day-freshlook-mystic-blue-right/
https://kefan-optics.com/shop/1-day-freshlook-mystic-blue-left/

Your plugin can get the data correctly if I add the product trough the WordPress site  but I don't know how to add that type of  item from the API through the `endpoint` `add-item` from you plugin

The response I get from `get-cart` for this product it's the above on the issue.

**Comment by seb86** [comment]
@heshaShawky Yeah it's a bit difficult with all those encrypted keys. Have you asked Yith what the encrypted keys are?

**Comment by heshaShawky** [comment]
It's available as metadata on the parent product I can get it through woocommerce api.

**Comment by seb86** [comment]
So you have the information then, correct?

**Comment by heshaShawky** [comment]
Yes just the `cart_item_key` is missing with me it's the cart item id how do I get that

**Comment by seb86** [comment]
Just using the API as it I don't think you can get the `cart_item_key` to pass as a variable. It's the same as the container so you may not need it. But if you do, you will have to filter the cart contents using `cocart_cart_contents`. You can do this by identifying the product type and checking the data as conditions to apply what you need.

Checkout the [tweaks repository](https://github.com/co-cart/co-cart-tweaks) for an example.

**Comment by heshaShawky** [comment]
Ok, When I send more than one request I get cors error ( parent product and they children ) 

I get success for the parent and error with the children a cors error

**Comment by seb86** [comment]
Can you share any further details on the error and show me what you have done?

**Comment by heshaShawky** [comment]
I figure out an easier solution but I don't know how to do it yet! 

I need to do a custom endpoint that adds the product to the cart using this form headers 
 
I got those headers from clciking the add to cart button in the product page at the site.
```
ywcp_selection[153CE4EE-C1A0-6D39-9AD5-58B51C5AB306]: -1
attribute_pa_sphere: 7-50
ywcp_variation_id[153CE4EE-C1A0-6D39-9AD5-58B51C5AB306]: 124138
ywcp_quantity[153CE4EE-C1A0-6D39-9AD5-58B51C5AB306]: 1
ywcp_selected_product_value[153CE4EE-C1A0-6D39-9AD5-58B51C5AB306]: 102523
ywcp_selection[471BAD03-9C3B-B44E-8584-348A5F33F8A6]: -1
attribute_pa_sphere: 7-00
ywcp_variation_id[471BAD03-9C3B-B44E-8584-348A5F33F8A6]: 110356
ywcp_quantity[471BAD03-9C3B-B44E-8584-348A5F33F8A6]: 1
ywcp_selected_product_value[471BAD03-9C3B-B44E-8584-348A5F33F8A6]: 102552
quantity: 1
add-to-cart: 102491
```

for further details check my question here to: 
https://stackoverflow.com/questions/58860768/woocommerce-how-to-add-custom-type-product-to-cart-with-ajax-by-user-jwt-token

**Comment by heshaShawky** [comment]
I'm sending the following to endpoint `add-item` but it's just returning the parent product not including the children: 

```
{
      cart_item_data: {
        ywcp_selection: {
          '153CE4EE-C1A0-6D39-9AD5-58B51C5AB306': 102523,
          '471BAD03-9C3B-B44E-8584-348A5F33F8A6': 102523
        },
        ywcp_variation_id: {
          '153CE4EE-C1A0-6D39-9AD5-58B51C5AB306': 124138,
          '471BAD03-9C3B-B44E-8584-348A5F33F8A6': 110356
        },
        ywcp_quantity: {
          '153CE4EE-C1A0-6D39-9AD5-58B51C5AB306': 1,
          '471BAD03-9C3B-B44E-8584-348A5F33F8A6': 1
        }, 
        ywcp_selected_product_value: {
          '153CE4EE-C1A0-6D39-9AD5-58B51C5AB306': 102523,
          '471BAD03-9C3B-B44E-8584-348A5F33F8A6': 102552
        }
      },
      quantity: 1,
      product_id: 102491,
    }
```

**Comment by seb86** [comment]
Closed based on the [request to support YITH Composite Products](https://github.com/co-cart/co-cart/issues/86)
