### ISSUE TITLE
Adding type of products composite to your api

### ISSUE THREAD

**Issue by heshaShawky** [co-cart/co-cart#86]
**Is your enhancement request related to a problem? Please describe.**
Your API just support the defaults products type such as `simple` or `variable` products

I'm working on a custom type product ( `yith-composite` ) and seems your plugin not support it. 

**Describe the solution you'd like**
Modifying the add-item endpoint so become compatible with the yith-composite products if possible 

I contacted the yith team and told me to check the class `class.yith-wcp-cart.php` but couldn't help as I don't know how to get it compatible with your API

**Comment by seb86** [comment]
Hi @heshaShawky 

I am working on supporting other WooCommerce extensions. As you are the first to request YITH Composite Products I will add it to the public roadmap.

Thank you for your request.

https://trello.com/c/IoJ48CZY/51-yith-composite-products

**Comment by heshaShawky** [comment]
Is there a way to hook the `add-item` endpoint to customize it?. 

I got this response from **yith team** and need to know how to hook a function into your `add-item` end-point

> Probably you can develop a function to replicate the "add_child_items" method of the "YITH_WCP_Cart" class that you can find in "class.yith-wcp-cart.php" file.
> How you can see, this method uses the WooCoomerce action "woocommerce_add_to_cart" and the filter "woocommerce_add_cart_item_data".


Thanks.

**Comment by seb86** [comment]
The only thing that I have supported with the current release is to pass the custom item data via the optional parameter. In the upcoming version I have made further improvements to include more options for developers to filter and hook in data so I recommend that you keep an eye for the next release were I can assist you further should it be needed.

**Comment by heshaShawky** [comment]
Hi there again, 

Is there a way to get the cart items from your plugin with PHP.

something like `WC()->cart->get_cart()` this not working for me it gets old items after I adding a product need to send 2 times to get the latest data

thanks.
