### ISSUE TITLE
Variable products need more validation before being added to cart.

### ISSUE THREAD

**Issue by mfcanovas** [co-cart/co-cart#87]
#  Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of CoCart on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. Call to add-item endpoint passing the id of a variable product instead of one of the variations
2. The product is added to cart

## Expected/actual behaviour

When I try to add to cart a variable product, the product is being added.

I was expecting to get an error as variable product should not be added to cart without selecting a variation.

## Isolating the problem

- [X] This bug happens with only WooCommerce and CoCart plugin are active.
- [X] This bug happens with a default WordPress theme active.
- [ ] This bug happens with the WordPress theme Storefront active.
- [X] This bug happens with the latest release of WooCommerce active.
- [X] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
```
Go to "WooCommerce > System Status then copy and paste the system status report here.
```
</details>

**Comment by seb86** [comment]
So more validation is required via the REST API as the core of WooCommerce does the validation via the JS not behind the scenes. Thank you for posting the issue @mfcanovas 

Your welcome to push a fix for this and get credit for this if you like. I'm currently improving other areas at this time.

**Comment by seb86** [comment]
Done. Commit b977569f7db8fae5ae735749b721227cdf98e494
