### ISSUE TITLE
Return cart totals in get-cart endpoint

### ISSUE THREAD

**Issue by crispossa** [co-cart/co-cart#89]
**Problem:**
Would be really more faster and performatic if the cart totals could be returned on get-cart endpoint, that way we don't need to call /totals endpoint on every cart mount on front-end, saving number of requests and lines of code.

**Possible solution:**
Maybe add a parameter to /get-cart EP to return totals.

**Comment by seb86** [comment]
The cart contents that returns via the get cart endpoint can be filtered so the totals could accidentally be removed either by you or a third part plugin. Will have to run some tests. It’s a good idea but might not be 100% full proof.

**Comment by seb86** [comment]
@crispossa Cart totals returned with the [Get Cart Enhanced](https://cocart.xyz/add-ons/get-cart-enhanced/) add-on.
