### ISSUE TITLE
Bulk add products

### ISSUE THREAD

**Issue by crispossa** [co-cart/co-cart#90]
Sometimes we already have a pre-populated cart (like programatically builded cart, for example) and to integrate with co-cart we need to add product by product, making dozen of requests and taking a lot of time for the cart to be ready.

Would be great if we have a simple endpoint where we can pass an array of itens to be added to cart.

**Comment by seb86** [comment]
It’s on the Roadmap for CoCart Pro. Not any easy thing to do as there many product types that have many conditions. Passing the data via the endpoint is one thing, the processing in the background is another.

**Comment by crispossa** [comment]
Agree with the complexity size of this story. If you need more info or use cases, count on me.
