### ISSUE TITLE
Return cart contents and cart totals when coupon is applied

### ISSUE THREAD

**Issue by crispossa** [co-cart/co-cart#92]
When we apply a new coupon we need to call /get-cart and /totals endpoints to get the cart itself with the coupon applied, which means more 2 requests to the API.
Would be great if the endpoint for apply coupon return this info.

**Comment by seb86** [comment]
The coupon option is only available in CoCart Pro not CoCart Lite. If you are a CoCart Pro customer please contact me (seb) directly via the COcart Slack channel for support or submit feedback via the feedback channel. Thank you.
