### ISSUE TITLE
More product data on get cart request

### ISSUE THREAD

**Issue by erback** [co-cart/co-cart#93]
**Describe the solution you'd like**
Thanks for a great plugin. Just started testing it out and it works like a charm. However, I would really like to be able to get more product related data in the "get cart" response.  For example I would like to be able to access the product category to render different cart item layouts on the frontend based on product category in cart. Right now I have to go through the product api in order to get more product details which generates unnecessary page request and delays rendering of the application. Is this something that you would be able to add support for? Maybe extra parameters can be added on demand just like the {"thumb": true} property on the get cart request.

**Comment by seb86** [comment]
Merry Christmas @erback 

You can use the available filters should you require to return additional data for the items in the cart.

I recommend checking the [tweaks plugin](https://github.com/co-cart/co-cart-tweaks) for examples.

Hope that helps.

**Comment by erback** [comment]
@seb86 thanks a lot and merry christmas!
